### ISSUE TITLE
Kerberos + ACL 支持问题

### ISSUE THREAD

**Issue by menghe999** [didi/KnowStreaming#1002]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

## 在这里提出你的问题
KS目前不支持配置Kerberos Kafka的ACL授权，这个部分什么时候能支持？
![image](https://user-images.githubusercontent.com/48467375/233588526-9e286b45-5754-41c3-a07b-0ca88df8b3a3.png)

**Comment by ZQKC** [comment]
> 

是的，后续可以优化一下。

**Comment by menghe999** [comment]
resolve
