### ISSUE TITLE
jmx配置端口不生效

### ISSUE THREAD

**Issue by szflfeiyu** [didi/KnowStreaming#1007]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个Bug。

 「   Y   /   N  」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   xxx </font>
* Operating System version :  <font size=4 color =red> xxx </font>
* Java version : <font size=4 color =red> xxx </font>

### 重现该问题的步骤

1. xxx
  在集群信息里配置了jmx端口为11001，服务启动后一直连接的9099，查看源码也没有发现这个配置，查看数据库里配置也是11001，但一直去连接9099，相当于配置不生效

2. xxx
   

3. xxx

### 实际结果

---

如果有异常，请附上异常Trace:

```
Just put your stack trace here!
```

**Comment by ZQKC** [comment]
> * [ ]  我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
> 
> 你是否希望来认领这个Bug。
> 
> 「 Y / N 」
> 
> ### 环境信息
> * KnowStreaming version :      xxx
> * Operating System version :   xxx
> * Java version :  xxx
> 
> ### 重现该问题的步骤
> 1. xxx
>    在集群信息里配置了jmx端口为11001，服务启动后一直连接的9099，查看源码也没有发现这个配置，查看数据库里配置也是11001，但一直去连接9099，相当于配置不生效
> 2. xxx
> 3. xxx
> 
> ### 预期结果
> ### 实际结果
> 如果有异常，请附上异常Trace:
> 
> ```
> Just put your stack trace here!
> ```

并非不生效，是优先使用了ZK上的JMX端口信息，如果ZK上没有这个信息，才会使用用户配置的这个信息。

**Comment by szflfeiyu** [comment]
是的，所以修改了表里zk的配置，但很快就被还原了，看了下代码是从ZK里取的信息，但由于使用的是MSK集群无法修改，所以修改代码让使用后面一段代码走jmxconfig但还是连接不上，有什么特殊配置？

**Comment by ZQKC** [comment]
> 

当前还没有，可以考虑在JmxConfig增加一些字段，来制定broker对应的具体端口。有兴趣的话，欢迎贡献这部分能力～
