### ISSUE TITLE
knowstreaming 查询kafka 消息优化

### ISSUE THREAD

**Issue by zhugezifang** [didi/KnowStreaming#1017]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

### 需要优化的功能点
knowstreaming 查询kafka 消息， 看代码 是去消费，然后 根据key 和value 进行查询是直接消费然后过滤，这样不会很慢吗？

**Comment by ZQKC** [comment]
> * [ ]  我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
> 
> ### 需要优化的功能点
> knowstreaming 查询kafka 消息， 看代码 是去消费，然后 根据key 和value 进行查询是直接消费然后过滤，这样不会很慢吗？
> 
> ### 建议如何优化

确实会比较慢，以及会损耗一些性能，但是，当前是这样考虑的：
1、Kafka服务端暂时不具备该能力，因此当前还是得考虑在客户端做；
2、查询Kafka消息，并非高频操作，而且KS是一个平台，只是查看一下消息，因此对性能要求也不是很高。

**Comment by zhugezifang** [comment]
> > * [ ]   我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
> > 
> > ### 需要优化的功能点
> > knowstreaming 查询kafka 消息， 看代码 是去消费，然后 根据key 和value 进行查询是直接消费然后过滤，这样不会很慢吗？
> > ### 建议如何优化
> 
> 确实会比较慢，以及会损耗一些性能，但是，当前是这样考虑的： 1、Kafka服务端暂时不具备该能力，因此当前还是得考虑在客户端做； 2、查询Kafka消息，并非高频操作，而且KS是一个平台，只是查看一下消息，因此对性能要求也不是很高。

好的，感谢建议哈
