### ISSUE TITLE
怎么关闭 metrics 收集

### ISSUE THREAD

**Issue by wangchaoforever** [didi/KnowStreaming#1018]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

## 在这里提出你的问题
如果只是为了使用 KnowStreaming 对 kafka 集群进行一些运维操作，不需要收集 cluster, broker, topic 等的 metrics，有没有什么方法可以关闭收集？

谢谢

**Comment by ZQKC** [comment]
> * [x]  我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
> 
> ## 在这里提出你的问题
> 如果只是为了使用 KnowStreaming 对 kafka 集群进行一些运维操作，不需要收集 cluster, broker, topic 等的 metrics，有没有什么方法可以关闭收集？
> 
> 谢谢

暂时没有。很多功能都依赖指标，因此，如果可以不关闭，建议不进行关闭。

**Comment by ZQKC** [comment]
无更多反馈，关闭该问题
