### ISSUE TITLE
修改用户密码报错

### ISSUE THREAD

**Issue by zzf1208** [didi/KnowStreaming#1034]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个Bug。

 「   Y   /   N  」

### 环境信息

* KnowStreaming version :   3.2
容器部署

### 重现该问题的步骤

修改用户密码提示：
2023-06-05 15:37:13.350 [http-nio-80-exec-6] WARN  class=org.mariadb.jdbc.message.server.ErrorPacket||Error: 1406-22001: Data too long for column 'phone' at row 1
![image](https://github.com/didi/KnowStreaming/assets/40556830/1274c1be-8ea9-496f-a264-418a1d49663d)

```

**Comment by ZQKC** [comment]
> * [ ]  我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
> 
> 你是否希望来认领这个Bug。
> 
> 「 Y / N 」
> 
> ### 环境信息
> * KnowStreaming version :   3.2
>   容器部署
> 
> ### 重现该问题的步骤
> 修改用户密码提示： 2023-06-05 15:37:13.350 [http-nio-80-exec-6] WARN class=org.mariadb.jdbc.message.server.ErrorPacket||Error: 1406-22001: Data too long for column 'phone' at row 1 ![image](https://user-images.githubusercontent.com/40556830/243293602-1274c1be-8ea9-496f-a264-418a1d49663d.png)

使用最新版试试

**Comment by zzf1208** [comment]
> > * [ ]   我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
> > 
> > 你是否希望来认领这个Bug。
> > 「 Y / N 」
> > ### 环境信息
> > 
> > * KnowStreaming version :   3.2
> >   容器部署
> > 
> > ### 重现该问题的步骤
> > 修改用户密码提示： 2023-06-05 15:37:13.350 [http-nio-80-exec-6] WARN class=org.mariadb.jdbc.message.server.ErrorPacket||Error: 1406-22001: Data too long for column 'phone' at row 1 ![image](https://user-images.githubusercontent.com/40556830/243293602-1274c1be-8ea9-496f-a264-418a1d49663d.png)
> 
> 使用最新版试试


大佬 您好，目前最新3.2.0版本的helm哪里可以下载呀，看官网最新只可以下载3.2.0的helm包，我这边是容器化部署

**Comment by zzf1208** [comment]
已找到，可以关闭任务了
