### ISSUE TITLE
Topic message预览，现在是按Timestamp列排序，需要按Offset排序，保证消息顺序性

### ISSUE THREAD

**Issue by ZQKC** [didi/KnowStreaming#1041]

**Comment by HZSUZJ** [comment]
能给出相关应用例子嘛，感觉按Timestamp列排序一样保证消息顺序性

**Comment by ZQKC** [comment]
> 能给出相关应用例子嘛，感觉按Timestamp列排序一样保证消息顺序性

![image](https://github.com/didi/KnowStreaming/assets/4694454/e682c546-42d7-472c-b5a6-cfb399879c93)

1、支持按照三个中的任意一个进行排序。
2、如果出现一样的情况，则优先把近的数据排在前面。

**Comment by HZSUZJ** [comment]
前端我来调试

**Comment by HZSUZJ** [comment]
已提交PR
