### ISSUE TITLE
[前端]v3.3分支源码启动，config-manager-fe页面报错

### ISSUE THREAD

**Issue by fuqingji** [didi/KnowStreaming#1052]
源码启动ks，config-manager-fe页面报错，layout-clusters-fe和后端正常。
ks分支：v3.3
node：12.20.0
npm：6.14.8
maven：3.6.3
jdk：1.8
系统：win11
命令行：bash/powershell
![c895368d8fb849bff21770ad88d5694](https://github.com/didi/KnowStreaming/assets/37463234/fa0ef777-cfe5-45f4-86ec-0ad1aaba5ade)
![image](https://github.com/didi/KnowStreaming/assets/37463234/1cdc5971-f098-45de-b9f2-f22c6084d73e)

使用npm run i 安装依赖时，报出大量告警如图及附件
![image](https://github.com/didi/KnowStreaming/assets/37463234/d57c120d-279b-419d-a857-49bc18ab589a)
完整
[warn.txt](https://github.com/didi/KnowStreaming/files/11729500/warn.txt)

**Comment by fuqingji** [comment]
@yangbajing @soarpenguin @Trinea @MingliangT

**Comment by ZQKC** [comment]
@lucasun 超哥有空帮忙看看啊

**Comment by fuqingji** [comment]
@lucasun 麻烦给看看呗
