### ISSUE TITLE
[前端]未勾选系统管理查看权限 但是依然可以查看系统管理

### ISSUE THREAD

**Issue by onecer** [didi/KnowStreaming#1053]
- [X] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个Bug。

 「    N  」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   3.3.0 </font>
* Operating System version :  <font size=4 color =red> centos7 </font>
* Java version : <font size=4 color =red> 11 </font>

### 重现该问题的步骤

1. 授权新用户，新角色 “多集群查看权限”

### 预期结果

隐藏掉系统管理菜单

### 实际结果

还能看到系统管理的内容

<img width="1901" alt="image" src="https://github.com/didi/KnowStreaming/assets/25147396/27072fd5-791d-4778-8016-6c8750550cb1">

---

如果有异常，请附上异常Trace:

```
Just put your stack trace here!
```

**Comment by HZSUZJ** [comment]
已提交pr(#1105)
