### ISSUE TITLE
SASL_SSL认证的集群应该如何配置

### ISSUE THREAD

**Issue by turnjian** [didi/KnowStreaming#1060]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

## 在这里提出你的问题
以下是我的集群配置：
{
  "security.protocol": "SASL_SSL",
  "sasl.mechanism": "PLAIN",
  "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"username\" password=\"password\";"
}
在进行管理集群时报：
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed

我需要在集群配置中指定truststore和keystore的位置和密码，请问如何修改集群配置，谢谢

**Comment by ZQKC** [comment]
> * [x]  我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
> 
> ## 在这里提出你的问题
> 以下是我的集群配置： { "security.protocol": "SASL_SSL", "sasl.mechanism": "PLAIN", "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username="username" password="password";" } 在进行管理集群时报： org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
> 
> 我需要在集群配置中指定truststore和keystore的位置和密码，请问如何修改集群配置，谢谢

生产消费客户端是如何配置的？

**Comment by turnjian** [comment]
> > * [x]   我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
> > 
> > ## 在这里提出你的问题
> > 以下是我的集群配置： { "security.protocol": "SASL_SSL", "sasl.mechanism": "PLAIN", "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username="username" password="password";" } 在进行管理集群时报： org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
> > 我需要在集群配置中指定truststore和keystore的位置和密码，请问如何修改集群配置，谢谢
> 
> 生产消费客户端是如何配置的？

"ssl.truststore.password": "PASSWORD"
"ssl.truststore.location": "PATH"
"ssl.keystore.type": "JKS"
"security.protocol": "SASL_SSL"
"sasl.mechanism": "PLAIN"
"sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"****\" password=\"****\";"

**Comment by ZQKC** [comment]
> "security.protocol": "SASL_SSL",
> "sasl.mechanism": "PLAIN",
> "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username="username" password="password";"
> }

参照你生产消费客户端的配置，将这个转成json填写在集群配置那块即可，KS会将这个json转成java的properties，然后作为kafka客户端的创建参数。

**Comment by turnjian** [comment]
> > "security.protocol": "SASL_SSL",
> > "sasl.mechanism": "PLAIN",
> > "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username="username" password="password";"
> > }
> 
> 参照你生产消费客户端的配置，将这个转成json填写在集群配置那块即可，KS会将这个json转成java的properties，然后作为kafka客户端的创建参数。

问题已经解决：配置文件如下：
{
  "ssl.keystore.type": "JKS",
  "security.protocol": "SASL_SSL",
  "ssl.protocol": "TLSv1.2",
  "ssl.truststore.location": "/path/client.trustkeystore.jks",
  "ssl.keystore.password": "password",
  "sasl.mechanism": "PLAIN",
  "ssl.enabled.protocols": "TLSv1.2",
  "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"username\" password=\"password\";",
  "ssl.keystore.location": "/path/client.keystore.jks",
  "ssl.truststore.password": "password,
  "ssl.endpoint.identification.algorithm": ""
}
