### ISSUE TITLE
如何查看更多的信息 

### ISSUE THREAD

**Issue by hanguanglinyun** [didi/KnowStreaming#1063]
![image](https://github.com/didi/KnowStreaming/assets/48739305/247fc8be-7796-4033-bd7e-430bfbd82c24)

这里只显示100条，想查看更多的历史信息

**Comment by ZQKC** [comment]
> ![image](https://user-images.githubusercontent.com/48739305/248524775-247fc8be-7796-4033-bd7e-430bfbd82c24.png)
> 
> 这里只显示100条，想查看更多的历史信息

1、什么场景需要更多历史信息？
2、企业版的messages那个功能应该可以满足你的需求，具体见ve_3.3.0版本，需要自行编译打包；

**Comment by ZQKC** [comment]
无更多反馈，关闭该Issue
