### ISSUE TITLE
KnowStreaming-3.0.0-beta.1 手动安装的, es为啥老是无法创建索引啊?

### ISSUE THREAD

**Issue by wantyougogo** [didi/KnowStreaming#1077]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

## 在这里提出你的问题
![图片](https://github.com/didi/KnowStreaming/assets/44570840/337a45e5-b449-43ef-bbe1-ccda5749df90)

![图片](https://github.com/didi/KnowStreaming/assets/44570840/981cda93-250f-47b3-a703-c23954a90e43)

https://doc.knowstreaming.com/product/2-quick-start#215%E6%89%8B%E5%8A%A8%E9%83%A8%E7%BD%B2
用这个教程手动安装的KnowStreaming服务, 隔一天就不好使, 查看日志发现创建不了索引, 这是什么原因呢?

**Comment by wantyougogo** [comment]
![图片](https://github.com/didi/KnowStreaming/assets/44570840/fd07ceb9-3413-4046-b7d6-e929315c4696)
![Uploading 图片.png…]()

平台上就各种没有数据

**Comment by ZQKC** [comment]
> * [ ]  我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
> 
> ## 在这里提出你的问题
> ![图片](https://user-images.githubusercontent.com/44570840/250791167-337a45e5-b449-43ef-bbe1-ccda5749df90.png)
> 
> ![图片](https://user-images.githubusercontent.com/44570840/250791643-981cda93-250f-47b3-a703-c23954a90e43.png)
> 
> https://doc.knowstreaming.com/product/2-quick-start#215%E6%89%8B%E5%8A%A8%E9%83%A8%E7%BD%B2 用这个教程手动安装的KnowStreaming服务, 隔一天就不好使, 查看日志发现创建不了索引, 这是什么原因呢?

辛苦使用最新版本，beta版本还是测试版本。索引创建失败，也有可能是es集群的shard满了。

**Comment by wantyougogo** [comment]
好的, 那我用最新版本搞一下试试看. 感谢!
