### ISSUE TITLE
BrokerConfigServiceImpl类中的getBrokerConfigByZKClient方法一定返回空列表

### ISSUE THREAD

**Issue by myloverwdm** [didi/KnowStreaming#1086]
```
    private Result<List<KafkaConfigDetail>> getBrokerConfigByZKClient(VersionItemParam itemParam) {
        BrokerParam param = (BrokerParam) itemParam;
        Result<Properties> propertiesResult = this.getBrokerConfigByZKClient(param.getClusterPhyId(), param.getBrokerId());
        if (propertiesResult.failed()) {
            return Result.buildFromIgnoreData(propertiesResult);
        }
        return Result.buildSuc(KafkaConfigConverter.convert2KafkaBrokerConfigDetailList(
                new ArrayList<>(),
                propertiesResult.getData()
        ));
    }


public static List<KafkaConfigDetail> convert2KafkaBrokerConfigDetailList(List<String> configNameList, Properties properties) {
        List<KafkaConfigDetail> configList = new ArrayList<>();
        for (String configName: configNameList) {
            KafkaConfigDetail config = new KafkaConfigDetail();
            config.setName(configName);
            config.setValue(properties.getProperty(configName));
            config.setConfigSource(DescribeConfigsResponse.ConfigSource.TOPIC_CONFIG.ordinal());

            ConfigDef.ConfigKey configKey = KafkaConstant.KAFKA_ALL_CONFIG_DEF_MAP.get(configName);
            if (configKey != null) {
                config.setDocumentation(configKey.documentation);
                config.setDefaultValue(configKey.defaultValue == null? "": configKey.defaultValue.toString());
                config.setOverride(config.getValue() != null && config.getValue().equals(configKey.defaultValue));
                config.setConfigType(configKey.type.ordinal());
            } else {
                config.setDocumentation(null);
                config.setDefaultValue(null);
                config.setOverride(null);
                config.setConfigType(null);
            }

            config.setSensitive(null);
            config.setReadOnly(null);
            configList.add(config);
        }

        return configList;
    }
```

在getBrokerConfigByZKClient方法中，调用KafkaConfigConverter.convert2KafkaBrokerConfigDetailList，传递第一个参数为空列表，KafkaConfigConverter.convert2KafkaBrokerConfigDetailList方法中对该列表进行遍历，然后返回，而参数为空列表是写死的，故该方法一定返回空列表，且KafkaConfigConverter.convert2KafkaBrokerConfigDetailList方法仅有该处使用到。

另：getBrokerConfigByZKClient方法中的代码：
for (Object key: properties.keySet()) {
  properties.getProperty((String) key);
}
不清楚该代码的目的是什么。校验所有的key都要是String类型，若不是String则强转失败吗？与之相同问题的还有TopicConfigServiceImpl类中的getTopicConfigByZKClient方法

**Comment by jiangminbing** [comment]
![1700928661311](https://github.com/didi/KnowStreaming/assets/33618883/4c82b1c8-56b8-41e6-be56-646b7ed38fed)
我对比了TopicConfigServiceImpl，BrokerConfigServiceImpl，这两个文件中的处理方法，和KafkaConfigConverer中convert2KafkaBrokerConfigDetailList，convert2KafkaTopicConfigDetailList  我的理解getBrokerConfigByZKClient中new ArrayList()的入参替换成kafka broker 的配置列表，处理方式是否是这里来处理的？

**Comment by ZQKC** [comment]
> ![1700928661311](https://private-user-images.githubusercontent.com/33618883/285602794-4c82b1c8-56b8-41e6-be56-646b7ed38fed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5NzIzNTMsIm5iZiI6MTcwMDk3MjA1MywicGF0aCI6Ii8zMzYxODg4My8yODU2MDI3OTQtNGM4MmIxYzgtNTZiOC00MWU2LWJlNTYtNjQ2YjdlZDM4ZmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDA0MTQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNDNjYmYwODA0OTZkZjAyMDFmZWUzOGRjN2M1YmQzOWJmMTliYjBhMDJlOGJkMDE2MmY0MTdkOGI0MjVkMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k7AlTFh5vnVnbue0oZlaolHQp1GFpo7pcEtWcifauhM) 我对比了TopicConfigServiceImpl，BrokerConfigServiceImpl，这两个文件中的处理方法，和KafkaConfigConverer中convert2KafkaBrokerConfigDetailList，convert2KafkaTopicConfigDetailList 我的理解getBrokerConfigByZKClient中new ArrayList()的入参替换成kafka broker 的配置列表，处理方式是否是这里来处理的？

是的

**Comment by jiangminbing** [comment]
![1701009369609](https://github.com/didi/KnowStreaming/assets/33618883/2699f3a9-45aa-41b1-8c9a-16c45a3d2225)
维护成类似TopicConfig0100这种配置的类信息？但是没找到相关BrokerConfig相关的信息？是否有指引类？
