### ISSUE TITLE
security下的users、acls未接入进权限管理，所有用户都可以查看密码和维护，需要加入权限管理

### ISSUE THREAD

**Issue by velee** [didi/KnowStreaming#1089]
<img width="1436" alt="image" src="https://github.com/didi/KnowStreaming/assets/8765691/0bdc9ed0-5ac8-45ee-9aa2-54a5a6bf5094">

<img width="1437" alt="image" src="https://github.com/didi/KnowStreaming/assets/8765691/0b9b0ea2-a20c-4d97-9007-d1caa4cbdf5b">

**Comment by luhea** [comment]
hello，velee，与此项类似的还有Topic的消息查看等权限，有些消息可能是敏感的不希望所有的人可以看所有的Topic，而是希望每个租户可以查看固定的Topic和cg等信息。是否可以考虑在页面权限的基础上加入数据权限？这一点在老版本的Logi-KM是可以的。

**Comment by ZQKC** [comment]
> hello，velee，与此项类似的还有Topic的消息查看等权限，有些消息可能是敏感的不希望所有的人可以看所有的Topic，而是希望每个租户可以查看固定的Topic和cg等信息。是否可以考虑在页面权限的基础上加入数据权限？这一点在老版本的Logi-KM是可以的。

辛苦单独提一个issue，你提的这块属于数据权限，需要对权限体系进行设计之后才能进行开发。

**Comment by ZQKC** [comment]
#1095
