### ISSUE TITLE
kafka使用kraft模式部署，在新增ACL时报错，Caused by:java.lang.IlleguementException:Could not find a 'KafkaClient' entry in the JAAS config' is not set

### ISSUE THREAD

**Issue by JieJieNiDeAi** [didi/KnowStreaming#1091]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

## 在这里提出你的问题
问题：新增ACL时日志报错，Caused by:java.lang.IlleguementException:Could not find a 'KafkaClient' entry in the JAAS config' is not set

kafka 版本为：3.4.1 部署方式kraft模式，无zookeeper
knowStreaming版本:3.3.0
在kafka的config目录下 增加了 kafk_server_jaas.conf内容：
KafkaServer {
	org.apache.kafka.common.security.plain.PlainLoginModule required serviceName="mycluer"
	username="producer"
	password="producerpwd";
};

KafkaClient {
	org.apache.kafka.common.security.plain.PlainLoginModule required
	username="producer"
	password="producerpwd";
};

**Comment by ZQKC** [comment]
> * [x]  我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
> 
> ## 在这里提出你的问题
> 问题：新增ACL时日志报错，Caused by:java.lang.IlleguementException:Could not find a 'KafkaClient' entry in the JAAS config' is not set
> 
> kafka 版本为：3.4.1 部署方式kraft模式，无zookeeper knowStreaming版本:3.3.0 在kafka的config目录下 增加了 kafk_server_jaas.conf内容： KafkaServer { org.apache.kafka.common.security.plain.PlainLoginModule required serviceName="mycluer" username="producer" password="producerpwd"; };
> 
> KafkaClient { org.apache.kafka.common.security.plain.PlainLoginModule required username="producer" password="producerpwd"; };

KS的接入集群时，集群配置填写的内容是？

**Comment by JieJieNiDeAi** [comment]
> > * [x]   我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
> > 问题：新增ACL时日志报错，Caused by:java.lang.IlleguementException:Could not find a 'KafkaClient' entry in the JAAS config' is not set
> > kafka 版本为：3.4.1 部署方式kraft模式，无zookeeper knowStreaming版本:3.3.0 在kafka的config目录下 增加了 kafk_server_jaas.conf内容： KafkaServer { org.apache.kafka.common.security.plain.PlainLoginModule required serviceName="mycluer" username="producer" password="producerpwd"; };
> > KafkaClient { org.apache.kafka.common.security.plain.PlainLoginModule required username="producer" password="producerpwd"; };
> 
> KS的接入集群时，集群配置填写的内容是？
集群配置是这样写的：
{
"security.protocol":"SASL_PLAINTEXT"
"sasl.jaas.config":"org.apache.kafka.common.security.plain.PlainLoginModule required \
    username="admin" 
    password="admin-secret" ;"
}

**Comment by JieJieNiDeAi** [comment]
> > * [x]   我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
> > 
> > ## 在这里提出你的问题
> > 问题：新增ACL时日志报错，Caused by:java.lang.IlleguementException:Could not find a 'KafkaClient' entry in the JAAS config' is not set
> > kafka 版本为：3.4.1 部署方式kraft模式，无zookeeper knowStreaming版本:3.3.0 在kafka的config目录下 增加了 kafk_server_jaas.conf内容： KafkaServer { org.apache.kafka.common.security.plain.PlainLoginModule required serviceName="mycluer" username="producer" password="producerpwd"; };
> > KafkaClient { org.apache.kafka.common.security.plain.PlainLoginModule required username="producer" password="producerpwd"; };
> 
> KS的接入集群时，集群配置填写的内容是？

{
"security.protocol":"SASL_PLAINTEXT"
"sasl.jaas.config":"org.apache.kafka.common.security.plain.PlainLoginModule required \
    username="admin" 
    password="admin-secret" ;"
}

**Comment by JieJieNiDeAi** [comment]
> > * [x]   我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
> > 
> > ## 在这里提出你的问题
> > 问题：新增ACL时日志报错，Caused by:java.lang.IlleguementException:Could not find a 'KafkaClient' entry in the JAAS config' is not set
> > kafka 版本为：3.4.1 部署方式kraft模式，无zookeeper knowStreaming版本:3.3.0 在kafka的config目录下 增加了 kafk_server_jaas.conf内容： KafkaServer { org.apache.kafka.common.security.plain.PlainLoginModule required serviceName="mycluer" username="producer" password="producerpwd"; };
> > KafkaClient { org.apache.kafka.common.security.plain.PlainLoginModule required username="producer" password="producerpwd"; };
> 
> KS的接入集群时，集群配置填写的内容是？
内容如下：
{
"security.protocol":"SASL_PLAINTEXT"
"sasl.jaas.config":"org.apache.kafka.common.security.plain.PlainLoginModule required \
    username="producer" 
    password="producerpwd" ;"
}

**Comment by JieJieNiDeAi** [comment]
> > * [x]   我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
> > 
> > ## 在这里提出你的问题
> > 问题：新增ACL时日志报错，Caused by:java.lang.IlleguementException:Could not find a 'KafkaClient' entry in the JAAS config' is not set
> > kafka 版本为：3.4.1 部署方式kraft模式，无zookeeper knowStreaming版本:3.3.0 在kafka的config目录下 增加了 kafk_server_jaas.conf内容： KafkaServer { org.apache.kafka.common.security.plain.PlainLoginModule required serviceName="mycluer" username="producer" password="producerpwd"; };
> > KafkaClient { org.apache.kafka.common.security.plain.PlainLoginModule required username="producer" password="producerpwd"; };
> 
> KS的接入集群时，集群配置填写的内容是？

内容如下：
{
"security.protocol":"SASL_PLAINTEXT",
"sasl.jaas.config":"org.apache.kafka.common.security.plain.PlainLoginModule required
username="producer"
password="producerpwd" ;"
}

**Comment by ZQKC** [comment]
与 #1092 相似，无更多反馈，关闭该问题。
