### ISSUE TITLE
扩分区之后，能不能把之前的分区消息，重新分配呢？

### ISSUE THREAD

**Issue by zhugezifang** [didi/KnowStreaming#1100]
- [ ] 我在 [issues](https://github.com/didi/KnowStreaming/issues) 中并未搜索到与此相关的功能需求。
- [ ] 我在 [release note](https://github.com/didi/KnowStreaming/releases) 已经发布的版本中并没有搜到相关功能.

## 这里描述需求

目前ks上实现了扩分区，但是没有实现之前的消息重新分配？

**Comment by zhugezifang** [comment]
同理：目前平台不能实现缩分区？

**Comment by ZQKC** [comment]
> 同理：目前平台不能实现缩分区？

kafka暂时不支持缩分区，以及对已经落盘的数据迁移到其他分区去。所以，平台暂时支持不了。

**Comment by zhugezifang** [comment]
> > 同理：目前平台不能实现缩分区？
> 
> kafka暂时不支持缩分区，以及对已经落盘的数据迁移到其他分区去。所以，平台暂时支持不了。

https://blog.csdn.net/a13568hki/article/details/116136622  这个不是支持的吗？

**Comment by ZQKC** [comment]
> > > 同理：目前平台不能实现缩分区？
> > 
> > 
> > kafka暂时不支持缩分区，以及对已经落盘的数据迁移到其他分区去。所以，平台暂时支持不了。
> 
> https://blog.csdn.net/a13568hki/article/details/116136622 这个不是支持的吗？

迁移仅仅是迁移整个分区，不会把数据从分区1迁移到分区2。
