### ISSUE TITLE
kafka消费组重置功能需求

### ISSUE THREAD

**Issue by luhea** [didi/KnowStreaming#1112]
- [x] 我在 [issues](https://github.com/didi/KnowStreaming/issues) 中并未搜索到与此相关的功能需求。
- [x] 我在 [release note](https://github.com/didi/KnowStreaming/releases) 已经发布的版本中并没有搜到相关功能.

你是否希望来认领这个Feature。

「   Y   /   N  」N

## 这里描述需求

KS version：3.3.0  kafka：2.7.1
当前为空的

1、当前版本的KS不支持重置到earlist，只支持重置到latest，如图：
![image](https://github.com/didi/KnowStreaming/assets/87756800/0fa6e896-276d-4779-b793-61e9ec5f9514)
2、kafka的消费组状态为Empty时候可以重置offset，当前重置时候，获取不到Topic。且当前只有Actice的cg才能重置。如图：
![image](https://github.com/didi/KnowStreaming/assets/87756800/8b405931-27e6-4165-8e49-ee845d5e72c0)
![image](https://github.com/didi/KnowStreaming/assets/87756800/e972271d-b8e2-49bb-a1ce-34da4fb5dd1f)
3、对于补数的场景，可以随意指定一个消费者组重置任意一个Topic的offset，当前不支持。
4、建议查看offset时候，增加刷新按钮，方便用户准确定位lag

**Comment by ZQKC** [comment]
> 

1、https://github.com/didi/KnowStreaming/issues/1039
2、Active的CG不能进行重置。如果没有Topic，是不是没有使用该CG去消费该Topic，或者未提交offset？
3、新需求，辛苦单独提一个Issue；
4、下一个版本会有；

**Comment by ZQKC** [comment]
新需求已提Issue，其余已处理，关闭该Issue
