### ISSUE TITLE
yml文件mysql密码明文存储

### ISSUE THREAD

**Issue by zwc401** [didi/KnowStreaming#1113]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个优化建议。

 「   Y   /   N  」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   xxx </font>
* Operating System version :  <font size=4 color =red> xxx </font>
* Java version : <font size=4 color =red> xxx </font>

### 需要优化的功能点
km-dist/docker/docker-compose.yml, /conf/application.yml两处mysql密码明文存储

### 建议如何优化
出于安全考虑，不建议密码明文存储，建议加密后存储或者从配置文件读取

**Comment by zhibinF** [comment]
我来认领这个优化建议，可以assign给我

**Comment by ZQKC** [comment]
> 我来认领这个优化建议，可以assign给我

辛苦关注一下该功能的增加不能影响已有的使用习惯。

**Comment by zhibinF** [comment]
> 

好的好的 我去调研下
