### ISSUE TITLE
官网证书过期

### ISSUE THREAD

**Issue by mingming-cn** [didi/KnowStreaming#1118]
1. 官网 https://knowstreaming.com/ 证书过期。
2. 使用 http://knowstreaming.com/ 访问时提示 “该网站暂时无法访问”。
3. Helm包 http://download.knowstreaming.com/charts/knowstreaming-manager-0.1.5.tgz 访问时提示  “该网站暂时无法访问”。

**Comment by ximply** [comment]
+1

**Comment by ZQKC** [comment]
@PenceXie 辛苦关注一下

**Comment by FOWind** [comment]
<img width="590" alt="image" src="https://github.com/didi/KnowStreaming/assets/13653453/e6ebd649-fa62-4cbc-b551-7d9b660d967c">
证书还没更新
