### ISSUE TITLE
在线体验地址用户名密码验证错误

### ISSUE THREAD

**Issue by magestacks** [didi/KnowStreaming#1136]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

## 在这里提出你的问题

您好，通过知识星球地址看到咱们账号/密码： admin / admin2022_    但是无法登录，提示报错。
登录地址：https://demo.knowstreaming.com/

<img width="508" alt="image" src="https://github.com/didi/KnowStreaming/assets/77398366/d1623047-437d-412c-ae7e-8c1ade05e774">

**Comment by iamxiaofu** [comment]
好像admin/admin可以登录

**Comment by ZQKC** [comment]
可以使用admin/admin登陆，知识星球后续我们修改一下。

**Comment by magestacks** [comment]
感谢两位大佬，已成功登录。
