### ISSUE TITLE
KnowStream的Controller显示延迟

### ISSUE THREAD

**Issue by iamxiaofu** [didi/KnowStreaming#1137]
- [ ] 我在 [issues](https://github.com/didi/KnowStreaming/issues) 中并未搜索到与此相关的功能需求。
- [ ] 我在 [release note](https://github.com/didi/KnowStreaming/releases) 已经发布的版本中并没有搜到相关功能.

你是否希望来认领这个Feature。

「   N 」

## 这里描述需求
<我在通过ui连接到Kraft模式的kafka集群后，发现在broker下的controller查看controller所在节点信息时，与实际controller信息显示有延迟，大概一分钟左右，对比的信息为软件UI for Apache Kafka提供的，且controller数据一直每隔一分钟或者两分钟在节点中变化，实际查看quorum-state文件controller节点并没有发生变化，希望可以进行优化>

**Comment by Hatsuhikari** [comment]
+1，希望加强一下对Kraft的适配，kraft模式下显示controller一直在变化，基本1分钟变一次，但实际上没有变化，而且Cluster健康状态还会监测ZK脑裂情况，也一直是未通过状态

**Comment by iamxiaofu** [comment]
> +1，希望加强一下对Kraft的适配，kraft模式下显示controller一直在变化，基本1分钟变一次，但实际上没有变化，而且Cluster健康状态还会监测ZK脑裂情况，也一直是未通过状态

是的，一分钟 两分钟偶尔三分钟变，虽然数据不多，但是看着下面的数字很烦哈哈，也判断不了实时的controller，我看了下UI for Apache Kafka显示的controller也是在变的，可能是配了zk的通病
