### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by xiaoqiqiya** [didi/KnowStreaming#1139]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个Bug。

 「   Y   /   N  」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   xxx </font>
* Operating System version :  <font size=4 color =red> xxx </font>
* Java version : <font size=4 color =red> xxx </font>

### 重现该问题的步骤

1. xxx
   Caused by: java.sql.SQLSyntaxErrorException: (conn=3) Table 'know_streaming.ks_ha_active_standby_relation' doesn't exist

2. xxx
   

3. xxx

### 实际结果

---

如果有异常，请附上异常Trace:

```
Just put your stack trace here!
```

**Comment by ZQKC** [comment]
> * [ ]  我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
> 
> 你是否希望来认领这个Bug。
> 
> 「 Y / N 」
> 
> ### 环境信息
> * KnowStreaming version :      xxx
> * Operating System version :   xxx
> * Java version :  xxx
> 
> ### 重现该问题的步骤
> 1. xxx
>    Caused by: java.sql.SQLSyntaxErrorException: (conn=3) Table 'know_streaming.ks_ha_active_standby_relation' doesn't exist
> 2. xxx
> 3. xxx
> 
> ### 预期结果
> ### 实际结果
> 如果有异常，请附上异常Trace:
> 
> ```
> Just put your stack trace here!
> ```

见版本升级手册。

**Comment by ZQKC** [comment]
无更多反馈，关闭该Issue
