### ISSUE TITLE
Overview指标文字错误

### ISSUE THREAD

**Issue by iamxiaofu** [didi/KnowStreaming#1150]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个Bug。

 「   N  」

### 环境信息

* KnowStreaming version : V3.3.0  <font size=4 color =red>   xxx </font>
* Operating System version :  <font size=4 color =red> xxx </font>
* Java version : <font size=4 color =red> xxx </font>

### 重现该问题的步骤

1. xxx
   

2. xxx
   

3. xxx

### 预期结果

集群每秒消息条数

### 实际结果

![image](https://github.com/didi/KnowStreaming/assets/92960846/b533b3cf-d6b9-4e52-aaee-de5a7eb7cece)

---

如果有异常，请附上异常Trace:

```
Just put your stack trace here!
```

**Comment by jiangminbing** [comment]
比较简单，我来解决

**Comment by ZQKC** [comment]
> 比较简单，我来解决

好的，感谢
