### ISSUE TITLE
WARNING: RMI TCP Accept-9999: accept loop for ServerSocket 遇到个异常

### ISSUE THREAD

**Issue by villay** [didi/KnowStreaming#1151]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

## 报错如下文
 kafka-server-start.sh: Sep 13, 2023 10:05:14 PM sun.rmi.transport.tcp.TCPTransport$AcceptLoop executeAcceptLoop
 kafka-server-start.sh: WARNING: RMI TCP Accept-9999: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=9999] throws
 kafka-server-start.sh: java.net.SocketException: Too many open files (Accept failed)
 kafka-server-start.sh: at java.net.PlainSocketImpl.socketAccept(Native Method)
 kafka-server-start.sh: at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
 kafka-server-start.sh: at java.net.ServerSocket.implAccept(ServerSocket.java:545)
 kafka-server-start.sh: at java.net.ServerSocket.accept(ServerSocket.java:513)
 kafka-server-start.sh: at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
 kafka-server-start.sh: at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
 kafka-server-start.sh: at java.lang.Thread.run(Thread.java:748)
 kafka-server-start.sh: Sep 13, 2023 10:05:14 PM sun.rmi.transport.tcp.TCPTransport$AcceptLoop executeAcceptLoop
 kafka-server-start.sh: WARNING: RMI TCP Accept-9999: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=9999] throws
 kafka-server-start.sh: java.net.SocketException: Too many open files (Accept failed)
 kafka-server-start.sh: at java.net.PlainSocketImpl.socketAccept(Native Method)
 kafka-server-start.sh: at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
 kafka-server-start.sh: at java.net.ServerSocket.implAccept(ServerSocket.java:545)
 kafka-server-start.sh: at java.net.ServerSocket.accept(ServerSocket.java:513)
 kafka-server-start.sh: at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
 kafka-server-start.sh: at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
 kafka-server-start.sh: at java.lang.Thread.run(Thread.java:748)
 kafka-server-start.sh: Sep 13, 2023 10:05:14 PM sun.rmi.transport.tcp.TCPTransport$AcceptLoop executeAcceptLoop
 kafka-server-start.sh: WARNING: RMI TCP Accept-9999: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=9999] throws
 kafka-server-start.sh: java.net.SocketException: Too many open files (Accept failed)
 kafka-server-start.sh: at java.net.PlainSocketImpl.socketAccept(Native Method)
 kafka-server-start.sh: at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
 kafka-server-start.sh: at java.net.ServerSocket.implAccept(ServerSocket.java:545)
 kafka-server-start.sh: at java.net.ServerSocket.accept(ServerSocket.java:513)
 kafka-server-start.sh: at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
 kafka-server-start.sh: at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
 kafka-server-start.sh: at java.lang.Thread.run(Thread.java:748)
 kafka-server-start.sh: Sep 13, 2023 10:05:14 PM sun.rmi.transport.tcp.TCPTransport$AcceptLoop executeAcceptLoop
 kafka-server-start.sh: WARNING: RMI TCP Accept-9999: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=9999] throws
 kafka-server-start.sh: java.net.SocketException: Too many open files (Accept failed)
 kafka-server-start.sh: at java.net.PlainSocketImpl.socketAccept(Native Method)
 kafka-server-start.sh: at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
 kafka-server-start.sh: at java.net.ServerSocket.implAccept(ServerSocket.java:545)
 kafka-server-start.sh: at java.net.ServerSocket.accept(ServerSocket.java:513)
 kafka-server-start.sh: at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
 kafka-server-start.sh: at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
 kafka-server-start.sh: at java.lang.Thread.run(Thread.java:748)
 kafka-server-start.sh: Sep 13, 2023 10:05:14 PM sun.rmi.transport.tcp.TCPTransport$AcceptLoop executeAcceptLoop
 kafka-server-start.sh: WARNING: RMI TCP Accept-9999: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=9999] throws
 kafka-server-start.sh: java.net.SocketException: Too many open files (Accept failed)
 kafka-server-start.sh: at java.net.PlainSocketImpl.socketAccept(Native Method)
 kafka-server-start.sh: at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
 kafka-server-start.sh: at java.net.ServerSocket.implAccept(ServerSocket.java:545)
 kafka-server-start.sh: at java.net.ServerSocket.accept(ServerSocket.java:513)
 kafka-server-start.sh: at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
 kafka-server-start.sh: at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
 kafka-server-start.sh: at java.lang.Thread.run(Thread.java:748)

# ulimit -n
1048576

**Comment by ZQKC** [comment]
@villay  Too many open files (Accept failed) 辛苦查看一下机器都打开了哪些文件具柄，具体如何查看可以搜一下啊。

**Comment by ZQKC** [comment]
无更多反馈，关闭该Issue
