### ISSUE TITLE
日志级别怎么调试

### ISSUE THREAD

**Issue by Harris1024** [didi/KnowStreaming#1156]
knowstreaming-manager服务每日刷出的日志大小几十个GB，太大了，怎么调试级别才好

**Comment by ZQKC** [comment]
> knowstreaming-manager服务每日刷出的日志大小几十个GB，太大了，怎么调试级别才好

可以配置一下logback文件，logback的配置及如何生效，可以网上搜一下。或者参看startup.sh和rest模块中的logback.xml文件

**Comment by trockxi** [comment]
docker部署传什么参数可以调整日志级别呢？
