### ISSUE TITLE
进入系统管理界面无数据展示，f12提示single-spa.min.js:142报错：application 'config' died in status LOADING_SOURCE_CODE: Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by githubhybaccount** [didi/KnowStreaming#1163]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个Bug。

 「   Y   /   N  」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   3.3.0 </font>
* Operating System version :  <font size=4 color =red> win10 </font>
* Java version : <font size=4 color =red> 8 </font>
* nodejs version : <font size=4 color =red> v12.20.0 </font>

### 重现该问题的步骤

访问 http://localhost:8080/config，前端浏览器提示single-spa.min.js:142报错：application 'config' died in status LOADING_SOURCE_CODE: Cannot assign to read only property 'exports' of object '#<Object>'
![image](https://github.com/didi/KnowStreaming/assets/20472549/e86bf4dc-2faf-485d-888a-b3d6f78edc9a)

希望大佬们帮忙解决，谢谢。

**Comment by Wyb7290** [comment]
#1159

**Comment by Wyb7290** [comment]
已提交PR (#1167)

**Comment by Kevin181** [comment]
@Wyb7290 大佬好，非常感谢你的热心解答！我也遇到这个问题，尝试了大佬#1159中提交的解决方案，但可能是环境或者还有其他配置原因，使用解决方法后再build或start也还是不行，报错依旧，希望大佬能帮忙看看，感谢！
**以下为修订的文件及内容**
`
km-console/packages/config-manager-fe/config/webpack.common.js

overrides: [
    // TODO：编译时需要做的事情更多，应该只针对目标第三方库
    {
      include: './node_modules',
      sourceType: 'unambiguous'
    }
  ],
`
**环境信息**

- KnowStreaming version : 3.3.0

- Operating System version : win11

- Java version : 8

- nodejs version : v12.22.12

**Comment by githubhybaccount** [comment]
@Wyb7290 感谢大佬，已经可以使用。

**Comment by Kevin181** [comment]
@githubhybaccount 你好，请问是按照大佬commit里对这个文件km-console/packages/config-manager-fe/config/webpack.common.js 进行修改后打包吗，还有做其他设置吗？非常感谢

**Comment by githubhybaccount** [comment]
> @githubhybaccount 你好，请问是按照大佬commit里对这个文件km-console/packages/config-manager-fe/config/webpack.common.js 进行修改后打包吗，还有做其他设置吗？非常感谢

是的，按照大佬只修改了km-console/packages/config-manager-fe/config/webpack.common.js，删除node_modules目录，重新编译打包就可以了。

**Comment by Kevin181** [comment]
> > @githubhybaccount 你好，请问是按照大佬commit里对这个文件km-console/packages/config-manager-fe/config/webpack.common.js 进行修改后打包吗，还有做其他设置吗？非常感谢
> 
> 是的，按照大佬只修改了km-console/packages/config-manager-fe/config/webpack.common.js，删除node_modules目录，重新编译打包就可以了。

感谢解答回复，也感谢大佬的方案。我本地也可以了。如果按照删除node_modules目录，重新install & build后还不行，推荐重启下电脑，可能就修复了（我本地就是如此）。
