### ISSUE TITLE
3.3.0版本connect页面没有接入connect集群按钮

### ISSUE THREAD

**Issue by zzf1208** [didi/KnowStreaming#1171]
![88a05785-e232-41d9-83e9-ee12b81b72b4](https://github.com/didi/KnowStreaming/assets/40556830/0c1f9628-ebf3-49dc-a9a3-671829bec9ce)
我这边需要使用replication ->miirirmakers功能，但是使用时发现要接入connect集群，但是connect页面没有接入的按钮，麻烦官方看一下。图片如上

**Comment by ZQKC** [comment]
> ![88a05785-e232-41d9-83e9-ee12b81b72b4](https://user-images.githubusercontent.com/40556830/275694023-0c1f9628-ebf3-49dc-a9a3-671829bec9ce.jpeg) 我这边需要使用replication ->miirirmakers功能，但是使用时发现要接入connect集群，但是connect页面没有接入的按钮，麻烦官方看一下。图片如上

如果该集群是connect集群，则会自动检测到并显示出来，不需要手动接入。

**Comment by zzf1208** [comment]
好的 明白了，我先关闭了
