### ISSUE TITLE
健康检查项中 "Zookeeper 未脑裂" 提示 "未通过"．

### ISSUE THREAD

**Issue by cobolbaby** [didi/KnowStreaming#1177]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个Bug。

 「   Y   /   N  」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   knowstreaming/knowstreaming-manager:0.8.0 </font>
* Operating System version :  <font size=4 color =red> xxx </font>
* Java version : <font size=4 color =red> xxx </font>

### 重现该问题的步骤

1. "接入集群" 的时候，只填写 Zookeeper 集群的一个节点
   
### 实际结果

健康检查项中 "Zookeeper 未脑裂" 提示 "未通过"．

---

如果有异常，请附上异常Trace:

```
Just put your stack trace here!
```

**Comment by ZQKC** [comment]
> * [ ]  我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
> 
> 你是否希望来认领这个Bug。
> 
> 「 Y / N 」
> 
> ### 环境信息
> * KnowStreaming version :      xxx
> * Operating System version :   xxx
> * Java version :  xxx
> 
> ### 重现该问题的步骤
> 1. "接入集群" 的时候，只填写 Zookeeper 集群的一个节点
> 
> ### 预期结果
> ### 实际结果
> 健康检查项中 "Zookeeper 未脑裂" 提示 "未通过"．
> 
> 如果有异常，请附上异常Trace:
> 
> ```
> Just put your stack trace here!
> ```

master分支应该已经修复了
