### ISSUE TITLE
离线安装不显示创建topic

### ISSUE THREAD

**Issue by lchaxian** [didi/KnowStreaming#1180]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个Bug。

 「   Y   /   N  」

### 环境信息

* KnowStreaming version :  3.3
* Operating System version : centos 7
* Java version : 11

### 重现该问题的步骤

1. xxx
  使用官网提供的离线安装脚本部署 3.2版本
访问后不存在topic 创建的按钮

![image](https://github.com/didi/KnowStreaming/assets/118433404/47c1f5bc-3295-432a-af95-224b4654e595)
![image](https://github.com/didi/KnowStreaming/assets/118433404/b2526acf-2d42-4857-bdc5-d75f3450f8cf)

2. xxx
   

3. xxx

### 实际结果

---

如果有异常，请附上异常Trace:

```
Just put your stack trace here!
```

**Comment by ZQKC** [comment]
后端有什么错误信息么？

**Comment by ZQKC** [comment]
无更多反馈，关闭该Issue
