### ISSUE TITLE
ACL使用问题

### ISSUE THREAD

**Issue by QQ853695231** [didi/KnowStreaming#1185]
最新版3.3.0里面，ACL无法选择指定的topic为啥？

**Comment by ZQKC** [comment]
> 最新版3.3.0里面，ACL无法选择指定的topic为啥？

已经解决了还是？

**Comment by QQ853695231** [comment]
> > 最新版3.3.0里面，ACL无法选择指定的topic为啥？
> 
> 已经解决了还是？

已经解决了，是我个人设置不对
