### ISSUE TITLE
希望KnowStreaming可以支持PLAIN认证方式

### ISSUE THREAD

**Issue by LionsArmstrong** [didi/KnowStreaming#1187]
- [x] 我在 [issues](https://github.com/didi/KnowStreaming/issues) 中并未搜索到与此相关的功能需求。
- [x] 我在 [release note](https://github.com/didi/KnowStreaming/releases) 已经发布的版本中并没有搜到相关功能.

你是否希望来认领这个Feature。

「   Y   」

## 这里描述需求

截止目前的[KnowStreaming]3.3版本。并没有针对认证方式的更多扩展。仅支持SCRAM的认证方式。希望KnowStreaming可以支持更多的认证方式。

**Comment by ZQKC** [comment]
> * [x]  我在 [issues](https://github.com/didi/KnowStreaming/issues) 中并未搜索到与此相关的功能需求。
> * [x]  我在 [release note](https://github.com/didi/KnowStreaming/releases) 已经发布的版本中并没有搜到相关功能.
> 
> 你是否希望来认领这个Feature。
> 
> 「 Y 」
> 
> ## 这里描述需求
> 截止目前的[KnowStreaming]3.3版本。并没有针对认证方式的更多扩展。仅支持SCRAM的认证方式。希望KnowStreaming可以支持更多的认证方式。

这块是指接入集群还是？接入集群的话，是支持的。

**Comment by ZQKC** [comment]
无更多反馈，关闭该Issue
