### ISSUE TITLE
在最新版本中接入Kraft模式kafka集群controller显示问题

### ISSUE THREAD

**Issue by iamxiaofu** [didi/KnowStreaming#1207]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个Bug。

 「  N  」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   V3.4.0 </font>
* Operating System version :  <font size=4 color =red>Centos7.9 </font>
* Kafka version : <font size=4 color =red> V3.5.1 </font>

### 重现该问题的步骤

1. 
![image](https://github.com/didi/KnowStreaming/assets/92960846/634199d1-2fa4-40cb-aab7-d89088d315f3)

   

2. 很有规律的一分钟一变，实际上在服务器上查看 /opt/kafka/kraft-combined-logs/__cluster_metadata-0/quorum-state，是没有变化的
   

### 实际结果

---

如果有异常，请附上异常Trace:

```
Just put your stack trace here!
```

**Comment by ZQKC** [comment]
当前是通过kafka客户端的接口获取controller信息的，需要确认一下接口返回的数据是否一分钟一变化，如果不是则ks这块是一个bug，如果接口返回的是存在一分钟一变化的，那么需要看一下kafka那块是怎么设计的。

**Comment by fantastywusheng** [comment]
https://stackoverflow.com/questions/74263083/kafka-find-controller-id-in-a-cluster-using-kraft-protocol/74782278#74782278
stackoverflow貌似有说，当使用KRaft时，集群不再只有一个控制器，而是集群中以"控制器"角色运行的节点都参与控制器元数据仲裁。

**Comment by ZQKC** [comment]
后面需要考虑在kraft模式下，这个页面后续该如何展示。

**Comment by ZQKC** [comment]
> 后面需要考虑在kraft模式下，这个页面后续该如何展示。

存在重复的建议，关闭该issue
