### ISSUE TITLE
淘宝npm老域名已下线 https://npm.taobao.org和http://registry.npmmirror.com

### ISSUE THREAD

**Issue by cuixianyu-github** [didi/KnowStreaming#1226]
http://npm.taobao.org和 http://registry.npm.taobao.org 将在 2022.06.30 号正式下线和停止 [DNS](https://so.csdn.net/so/search?q=DNS&spm=1001.2101.3001.7020) 解析。新域名为 npmmirror.com, 相关服务域名切换规则请参考：
http://npm.taobao.org => http://npmmirror.com
http://registry.npm.taobao.org => http://registry.npmmirror.com

**Comment by ZQKC** [comment]
> [http://npm.taobao.org和](http://npm.taobao.org%E5%92%8C) http://registry.npm.taobao.org 将在 2022.06.30 号正式下线和停止 [DNS](https://so.csdn.net/so/search?q=DNS&spm=1001.2101.3001.7020) 解析。新域名为 npmmirror.com, 相关服务域名切换规则请参考： http://npm.taobao.org => http://npmmirror.com http://registry.npm.taobao.org => http://registry.npmmirror.com

感谢建议，有兴趣的话，也欢迎提供pr进行修复

**Comment by jiangminbing** [comment]
![图片](https://github.com/didi/KnowStreaming/assets/33618883/a285b946-debf-441e-9d99-7a1cc2368c91)
这个pr校验不成功是这个原因吗

**Comment by ZQKC** [comment]
> ![图片](https://private-user-images.githubusercontent.com/33618883/334451296-f1bbcd18-fd3d-4476-9d57-1b06958095c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NTk4MjksIm5iZiI6MTcxOTc1OTUyOSwicGF0aCI6Ii8zMzYxODg4My8zMzQ0NTEyOTYtZjFiYmNkMTgtZmQzZC00NDc2LTlkNTctMWIwNjk1ODA5NWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDE0NTg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0ZDI1MzE0YTU0ZTY4Nzg0MzUzODRlZmRkODA5ZTVjNzFmOWE0ZGZiM2E3YmFmOTY4MjAwOWYzNjljOWYxMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rJuhwuXzAcY9DV-nMH2AYRVwEdFXha9_izcV0qMBj8U) 修改下这个就可以吧，如果是这个我顺手改下

嗯嗯，是的

**Comment by velee** [comment]
#1240
