### ISSUE TITLE
Topic level metric agg dsl should be sum not avg

### ISSUE THREAD

**Issue by ruanliang-hualun** [didi/KnowStreaming#1238]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个Bug。

 「   Y  」

### 问题描述
![4097c94bea1d928b5666644ccf9de2f](https://github.com/user-attachments/assets/ea86d083-41be-455e-b03c-b0c175404b3a)

**Comment by ruanliang-hualun** [comment]
pr：https://github.com/didi/KnowStreaming/pull/1239

**Comment by velee** [comment]
感谢您对开源的贡献，已合并
