### ISSUE TITLE
希望增加支持改动副本个数的特性

### ISSUE THREAD

**Issue by f7753** [didi/KnowStreaming#15]
一般来说，这个功能用途不是很大，因为通常默认就是3，但是实际中发现也有同学没注意这些，填写了1或者其他不合理的值，如果管理员审核的时候没注意，topic上线后还需要手动到机器上重新修改副本个数。

为增加Kafka管理功能的完备性和方便上述情况的处理，希望可以支持topic副本数修改，感谢

**Comment by cobolbaby** [comment]
+1

**Comment by ZHAOYINRUI** [comment]
在未来迭代的大版本中，计划补充上该功能。预计22年Q1发布

**Comment by ZQKC** [comment]
3.0版本已进行支持，可以下载源码进行打包尝鲜一下～
