### ISSUE TITLE
消费组详情增加total lag统计

### ISSUE THREAD

**Issue by ZHAOYINRUI** [didi/KnowStreaming#168]
页面位置：http://117.51.150.133:8080/kafka/topic/topic-detail?clusterId=4&topic=kmo_logi&consumerGroup=logi-kafka-km&location=broker&region=cn#4
![image](https://user-images.githubusercontent.com/51046167/106892029-78eabd00-6726-11eb-8f71-8520a1eafeff.png)

**Comment by chengang2** [comment]
请问该issue有人认领了吗？这个我这边可以做

**Comment by ZHAOYINRUI** [comment]
> 请问该issue有人认领了吗？这个我这边可以做

好的，那就辛苦由您来做这个需求。开发完成后，请提pr，由我们来验证、合并
再次感谢您能参与到滴滴Logi-KafkaManager开源共建中来～

**Comment by ZQKC** [comment]
最新的3.0上已具备maxLag的功能，可以尝鲜体验一下
