### ISSUE TITLE
建议推送提供一下hub.docker.com的公共镜像

### ISSUE THREAD

**Issue by nickfan** [didi/KnowStreaming#214]
建议推送提供一下hub.docker.com的公共镜像作为基础，大家好在此基础上做自定义改造。

**Comment by cobolbaby** [comment]
建议添加 github workflows

**Comment by ZQKC** [comment]
近期2.6.0版本我们看一下这个问题～

**Comment by ZQKC** [comment]
https://hub.docker.com/search?q=knowstreaming 欢迎尝鲜～
