### ISSUE TITLE
Broker列表的ID那一列，列名是否有必要修改为Broker-ID？

### ISSUE THREAD

**Issue by ZQKC** [didi/KnowStreaming#277]
如题

**Comment by Hongten** [comment]
因为是在Broker这个tab下面，这里的ID对应于broker id，大家都看的懂吧

**Comment by ZQKC** [comment]
> 因为是在Broker这个tab下面，这里的ID对应于broker id，大家都看的懂吧

还不够清晰明确的感觉，现在还是有部分刚刚接触Kafka的用户，对这个ID不是非常的清楚，所以看是否有必要小优化一下

**Comment by ZHAOYINRUI** [comment]
修改为：BrokerID

**Comment by ZHAOYINRUI** [comment]
文档会跟着大版本统一优化

**Comment by ZQKC** [comment]
3.x版本已进行修改
