### ISSUE TITLE
一个topic下线后，quota的配置信息仍然存在于zookeeper中

### ISSUE THREAD

**Issue by Hongten** [didi/KnowStreaming#278]
一个topic下线后，quota的配置信息仍然存在于zookeeper中
例如：Topic “testApp_1” 已经下线，但是quota的配置信息仍然存在

`
bin/kafka-configs.sh  --zookeeper mylocalip:2181 --describe --entity-type clients
Warning: --zookeeper is deprecated and will be removed in a future version of Kafka.
Use --bootstrap-server instead to specify a broker to connect to.
Configs for client-id 'appId_000004_sg.test_1' are producer_byte_rate=2097152,consumer_byte_rate=2097152
Configs for client-id 'appId_000010_sg.testApp_1' are
`

**Comment by ZQKC** [comment]
近期2.6.0版本我们处理一下该问题～

**Comment by ZQKC** [comment]
近期2.6.0版本我们处理一下该问题～

**Comment by ZQKC** [comment]
3.x版本已对该问题做了优化处理，欢迎尝鲜使用～
