### ISSUE TITLE
Fix Apache trademark violation in project name

### ISSUE THREAD

**Issue by vahidhashemian** [didi/KnowStreaming#325]
I am reaching out to you on behalf of Apache Kafka PMC.

In case you are not aware, the names of all Apache® projects, software products, and their logos are trademarks owned by the Apache Software Foundation. More info can be found here: https://www.apache.org/foundation/marks/faq/

According to the ASF trademark policy, the use of Logi-KafkaManager or "kafka manager" as used in the product's GitHub page is in violation and not permitted.

We would highly appreciate it if you could address this issue.

Thank you very much in advance for your consideration on this matter.

--Vahid Hashemian
on behalf of Apache Kafka Project Management Committee

PS. I've reached out privately to some of the active contributors of the project, but did not get a response.

**Comment by ZQKC** [comment]
we have received it. Let's see how to adjust it in the near future

**Comment by PenceXie** [comment]
We have completely eliminated "Kafka Manager"  in version 3.0, thanks
Welcome to try our new products("Know Streaming")
Know Streaming is an Apache Kafka Web UI for exploring messages, consumers, configurations and more with a focus on a good UI & UX.
