### ISSUE TITLE
Request to a rename to avoid Kafka trademark infringement.

### ISSUE THREAD

**Issue by wu-sheng** [didi/KnowStreaming#345]
Hi, Logi project maintainers 

First of all, thank you for setting a project around the Apache Kafka project. But I need to point out, 
**Kafka name and logo should not be used in your repo name, logi's logo, and many other places**. All these indicate explicitly this project is a part of Apache Kafka's component, but it isn't.

Could you work with the Apache Software Foundation, let's resolve this trademark issue?

Apache Software Foundation.

____

I could be your liaison if you need more clear context.

**Comment by PenceXie** [comment]
We have completely eliminated Kafka name and logo in version 3.0, thanks
Welcome to try our new products("[Know Streaming](https://demo.knowstreaming.com)")
Know Streaming is an Apache Kafka Web UI for exploring messages, consumers, configurations and more with a focus on a good UI & UX.
