### ISSUE TITLE
“国内”可选项是为了支持国际化还是为了支持多站点？

### ISSUE THREAD

**Issue by cobolbaby** [didi/KnowStreaming#347]
<img width="345" alt="屏幕快照 2021-07-07 下午11 36 56" src="https://user-images.githubusercontent.com/11460848/124788787-44508b00-df7c-11eb-9e2f-73540571b8dc.png">

**Comment by cobolbaby** [comment]
针对跨地域跨机房的场景，Kafka集群往往有很多套，此时Logi-KM的部署策略是什么？是用一套服务进行集中式管理还是分散部署分散管理？

**Comment by ZQKC** [comment]
都可以，这里可以是国内的什么机房，也可以是什么国家等

**Comment by cobolbaby** [comment]
我想配置多个地域，怎么配置呢？

**Comment by ZQKC** [comment]
> 我想配置多个地域，怎么配置呢？

前端请求中带上地域的标识，然后请求后端的时候，后端加一层依据标识进行请求转发的功能。前端具体的可以问一下 @lucasun

**Comment by ZQKC** [comment]
如有更多问题，欢迎入群(README中有群地址)交流～

**Comment by ZQKC** [comment]
2.x具备该能力，3.x后续如有需求，重新提issue即可，关闭当前issue
