### ISSUE TITLE
支持申请修改Topic的保存时间

### ISSUE THREAD

**Issue by cobolbaby** [didi/KnowStreaming#359]
![2021-08-02 10-13-21屏幕截图](https://user-images.githubusercontent.com/11460848/127795583-1a293539-c6c9-4765-a580-d33399c4b2a4.png)

除了 "申请配额" 以及 "申请分区" 以外， 其实常见的需求还有调整 "存留时间"，能否支持一下

**Comment by ZQKC** [comment]
> ![2021-08-02 10-13-21屏幕截图](https://user-images.githubusercontent.com/11460848/127795583-1a293539-c6c9-4765-a580-d33399c4b2a4.png)
> 
> 除了 "申请配额" 以及 "申请分区" 以外， 其实常见的需要还有调整 "存留时间"，能否支持一下

这块是期望在工单流程上支持还是简单的支持修改？

**Comment by cobolbaby** [comment]
"简单的修改"我的理解是指从运维管理的入口去改，您是这个意思？

我更倾向于"工单"

**Comment by ZHAOYINRUI** [comment]
修改topic保持时间的这个功能会在v3.0时支持，敬请期待～

**Comment by cobolbaby** [comment]
有预计的发布时间吗?

**Comment by ZQKC** [comment]
> 有预计的发布时间吗?

v3版本预计会在2022-06左右发布

**Comment by ZQKC** [comment]
2.x版本的需求，3.x不具备该功能，因此关闭该Issue
