### ISSUE TITLE
支持接入带kerberos认证的zookeeper kafka集群

### ISSUE THREAD

**Issue by gaoxiancan** [didi/KnowStreaming#363]
目前版本无法接入带有kerberos认证的zookeeper kafka集群

**Comment by ZHAOYINRUI** [comment]
支持接入zk集群，已经在我们的迭代计划中了，届时会跟随着产品重构一同发布

**Comment by mycode-zs** [comment]
现在有版本能支持带有kerberos认证的zookeeper kafka集群么？

**Comment by ZQKC** [comment]
> 现在有版本能支持带有kerberos认证的zookeeper kafka集群么？

3.3.0+版本可以，具体见FAQ和产品上的提示
