### ISSUE TITLE
"资源治理"任务flushExpiredTopic未能定时跑

### ISSUE THREAD

**Issue by cobolbaby** [didi/KnowStreaming#370]
服务一重启，资源治理下的信息就没了，需要手动调 Schedule 接口才能出来，怀疑 Schedule 模块有bug。

**Comment by ZQKC** [comment]
这些任务的执行周期被修改时，都是非持久化的，每次重启时，就会使用代码里面写死的配置。 看一下是否是因为这个原因导致的任务未能定时跑，后续我们看一下是否有必要持久化到DB中并支持修改。

**Comment by ZQKC** [comment]
无更多反馈，关闭该问题，有更多问题欢迎入群沟通交流

**Comment by cobolbaby** [comment]
> 这些任务的执行周期被修改时，都是非持久化的，每次重启时，就会使用代码里面写死的配置。 看一下是否是因为这个原因导致的任务未能定时跑，后续我们看一下是否有必要持久化到DB中并支持修改。

这是一个原因，但还有一种情况，服务运行一段时间以后，数据也没了，但手动再调一下接口又有了，这种情况比较奇怪，我还没有稳定复现。

**Comment by ZQKC** [comment]
> > 这些任务的执行周期被修改时，都是非持久化的，每次重启时，就会使用代码里面写死的配置。 看一下是否是因为这个原因导致的任务未能定时跑，后续我们看一下是否有必要持久化到DB中并支持修改。
> 
> 这是一个原因，但还有一种情况，服务运行一段时间以后，数据也没了，但手动再调一下接口又有了，这种情况比较奇怪，我还没有稳定复现。

手动调用一下接口，这个接口是？过期Topic是存储在topic_expired表里面的，可以关注一下这个表的数据变化。

**Comment by Huyueeer** [comment]
@ZQKC 我来回答
问题现象：服务重启后，专家服务->过期Topic中的数据会显示不全面，因为之前还有一个issue是过期Topic删除后实则没有真正删除，所以在列表里都是以上Topic；还有一个现象是，服务在运行一段时间后，也会发现过期Topic数据异常，显示不正确，不排除是否因为“过期Topic删除后实则没有真正删除”影响。
解决方式：我会在服务重启后在Swagger->RD-Schedule相关接口->调用flushExpiredTopic来显示过期Topic数据；

**Comment by ZQKC** [comment]
> @ZQKC 我来回答 问题现象：服务重启后，专家服务->过期Topic中的数据会显示不全面，因为之前还有一个issue是过期Topic删除后实则没有真正删除，所以在列表里都是以上Topic；还有一个现象是，服务在运行一段时间后，也会发现过期Topic数据异常，显示不正确，不排除是否因为“过期Topic删除后实则没有真正删除”影响。 解决方式：我会在服务重启后在Swagger->RD-Schedule相关接口->调用flushExpiredTopic来显示过期Topic数据；

1、第一个问题，已删除Topic依旧存在的问题，应该在2.5.0版本修复了，可以使用2.5.0版本验证一下。
2、第二个问题，需要手动触发flushExpiredTopic任务，这块可以观察一下是不是Task模块的所有任务被阻塞了，因此导致flushExpiredTopic任务未能被正常执行。如果是的话，可以检查一下被哪些集群阻塞了，以及后续我们会对任务增加超时时间。

**Comment by ZQKC** [comment]
长期无反馈，同时是2.x版本的问题，因此关闭该Issue
