### ISSUE TITLE
前端监控视图显示异常

### ISSUE THREAD

**Issue by Huyueeer** [didi/KnowStreaming#386]
LogiKM涉及到的监控视图貌似是存在bug，显示比较诡异
我在前端的一些页面中发现多次这样的图像，建议逐个排查一下，下图是“运维管控--集群列表--历史流量”发现的。
![image](https://user-images.githubusercontent.com/40758588/135019727-50b6b0fd-3bbf-4137-9434-898ee3d59223.png)

**Comment by cobolbaby** [comment]
请问一下，如果一个节点宕掉了，其他节点正常，此时流量曲线也比较异常，都归零了。

**Comment by ZHAOYINRUI** [comment]
好的，这个问题我们近期关注一下～

**Comment by ZHAOYINRUI** [comment]
该问题已修复，已发布在最新的版本中～

**Comment by Huyueeer** [comment]
@ZQKC 在新版本的验证中发现同样的问题，是否需要重新打开此issue
![image](https://user-images.githubusercontent.com/40758588/150898281-4af97459-ba48-4e11-8514-ffdd71dc3397.png)

**Comment by ZQKC** [comment]
感谢反馈，我跟进看一下当时是怎么解决该问题的，看是否有什么其他边界条件没有考虑到

**Comment by ZQKC** [comment]
@Hu

> @ZQKC 在新版本的验证中发现同样的问题，是否需要重新打开此issue ![image](https://user-images.githubusercontent.com/40758588/150898281-4af97459-ba48-4e11-8514-ffdd71dc3397.png)

感谢反馈。我们在Mac下验证无该问题，且使用你那边提供的数据无法在Mac下复现。了解到你那边的系统是Windows，我们再验证一下Windows下是否存在该问题后再对该Issue进行处理。

**Comment by ZQKC** [comment]
可以考虑使用3.0版本，2.x版本后续基本不再进行维护～
