### ISSUE TITLE
能否增加对Kafka Connector的监控

### ISSUE THREAD

**Issue by blooming** [didi/KnowStreaming#388]
Kafka Connect提供Restful和JMX两种监控接口
[Monitoring Kafka Connect and Connectors](https://docs.confluent.io/home/connect/monitoring.html)
目前和MQTT的集成，和Debezium的集成都需要用到Kafka Connect
Kafka Connect在Kafka生态中越来越重要
希望LogiKM能否提供一站式的监控服务
谢谢！

**Comment by ZHAOYINRUI** [comment]
Kafka connect的生态预计会在22年Q1的大版本中支持，敬请期待～

**Comment by ZQKC** [comment]
会在3.2版本中进行支持～

**Comment by ZQKC** [comment]
已在3.2版本中进行支持～
