### ISSUE TITLE
能不能添加一个基于消费组视角的topic消费详情

### ISSUE THREAD

**Issue by liu391447823** [didi/KnowStreaming#415]
KafkaEagle有类似的功能
![image](https://user-images.githubusercontent.com/11533344/147413263-666e5583-398f-4904-9e15-c3e5cbc9c6b2.png)
![image](https://user-images.githubusercontent.com/11533344/147413271-e0f009be-d331-4ea0-a7a4-2ba0e8615b3b.png)

**Comment by ZQKC** [comment]
收到，我们跟进看一下近期2.5.1版本的小迭代，是否将这个功能加上。

**Comment by liu391447823** [comment]
好的，期待ing

**Comment by liu391447823** [comment]
2.5.1大概什么时候发版

**Comment by ZHAOYINRUI** [comment]
该部分功能将会放在下一个大版本迭代（预计22年Q2）中实现～，敬请期待哈

**Comment by brodiehong** [comment]
> 2.5.1大概什么时候发版

我们最新版本已经具备这个功能😇

**Comment by ZQKC** [comment]
已具备该功能，关闭该Issue
