### ISSUE TITLE
普通用户是否禁止重置消费组offset

### ISSUE THREAD

**Issue by wanggc2019** [didi/KnowStreaming#418]
您好，我们在使用km时遇到一个问题就是km的用户角色有3个，普通用户，研发，运维，目前我们建了一个普通用户开放给业务使用，但是发现在topic消费组中，普通用户可以使用重置offset，虽然需要停止应用，才会生效，但是我们认为这个权限开放给业务还是不太适合，我们需要完全的一个只读的账号，普通用户只查看和提交工单。
请问，关于这块有没有什么好的建议？
![image](https://user-images.githubusercontent.com/44225658/147784547-65a18030-5340-4291-95fd-b5d121283022.png)

**Comment by ZQKC** [comment]
@ZHAOYINRUI  寅锐关注一下。我理解，从权限上来说，这块确实需要做一下管控，否则就像你说的，会出现可能被误操作了。

**Comment by wanggc2019** [comment]
any update?

**Comment by wanggc2019** [comment]
@ZHAOYINRUI @ZQKC 大佬，这个issue我们有更新吗？因为这个问题，km我们一直不敢完全开放给业务使用。

**Comment by ZHAOYINRUI** [comment]
由于考虑到普通用户（消费组使用者）也是会存在重置offset的场景，所以也是会开放给普通用户这个功能。但是，为了考虑到安全性，可以增加一个输入appid+密码（拥有该topic读写权限的appid）来确认一下身份

**Comment by ZHAOYINRUI** [comment]
该部分功能短期内没有纳入迭代的打算

**Comment by ZHAOYINRUI** [comment]
该部分功能短期内没有纳入迭代的打算～

**Comment by ZQKC** [comment]
3.x版本已对该问题做了优化处理，可以设置用户页面权限，欢迎尝鲜使用～

**Comment by ZQKC** [comment]
无更多反馈，关闭该Issue
