### ISSUE TITLE
旧版本未删除Topic信息清除计划

### ISSUE THREAD

**Issue by Huyueeer** [didi/KnowStreaming#454]
由于之前在2.4.2版本中存在删除Topic未同步删除DB信息，导致升级新版本后依旧存在之前不存在的Topic，显示在过期Topic中，有没有什么方法可以清理一下这种“幽灵Topic”。
![image](https://user-images.githubusercontent.com/40758588/150897416-03ee0b38-f202-44f6-bcd4-e3dfce7bb3dc.png)

**Comment by ZQKC** [comment]
接下来的2.6.1小版本中我们优化一下

**Comment by ZQKC** [comment]
3.x版本已对该问题做了优化处理，欢迎尝鲜使用～
