### ISSUE TITLE
数据采样异常

### ISSUE THREAD

**Issue by Huyueeer** [didi/KnowStreaming#460]
#### 先说背景:
Topic是自动创建的没有通过LogiKM，在集群接入LogiKM后，进行数据采样，发现不是空就是报错：
![image](https://user-images.githubusercontent.com/40758588/153814533-cce20db1-5bed-441f-b86d-ec4861ba7411.png)
但是我通过命令` kafka-console-consumer & kafka-run-class kafka.tools.GetOffsetShell`是可以消费到数据的：
![image](https://user-images.githubusercontent.com/40758588/153814699-ec2f3a2f-dca6-4561-bc20-3f052c427b02.png)
![image](https://user-images.githubusercontent.com/40758588/153815737-001e212a-2dc7-434d-b9a3-ade23501a4f2.png)

**Comment by ZQKC** [comment]
辛苦提供一下Kafka的版本信息，我们也验证一下

**Comment by Huyueeer** [comment]
@ZQKC kafka-5.5.2-ccs

**Comment by ZQKC** [comment]
> @ZQKC kafka-5.5.2-ccs

这个是confluent发布的kafka是吧？我们看一下啊

**Comment by Huyueeer** [comment]
@ZQKC hi，最近的错误修复会有新版本发布吗？

**Comment by ZQKC** [comment]
> @ZQKC hi，最近的错误修复会有新版本发布吗？

近期重点会在3.0版本的开发，2.x版本迭代近期暂无太多人力支持，采样这个问题，等3.0迭代完成后，我们看一下原因。近期老哥要是有空的话，也欢迎帮忙定位看一下原因，感谢。

**Comment by ZQKC** [comment]
3.x版本已对该问题做了优化处理，欢迎尝鲜使用，看是否还存在该问题～

**Comment by Huyueeer** [comment]
> 3.x版本已对该问题做了优化处理，欢迎尝鲜使用，看是否还存在该问题～

是的，已经得到解决
