### ISSUE TITLE
用户权限问题

### ISSUE THREAD

**Issue by stancycowen** [didi/KnowStreaming#485]
个人觉得用户角色定义的有点问题 之前也有人提过
研发人员可以删除修改运维人员的账号有点不合理
![image](https://user-images.githubusercontent.com/8426317/162407149-b0a17dbc-bedb-4b73-a9d7-52e1de56443c.png)
这种对用户的操作一般只有最高权限的角色才能操作
目前看来logikm的最高权限角色就是运维人员角色
个人拍脑袋的建议 
普通角色 只读权限 申请等权限
研发角色 更高的读权限 申请审批等
运维角色 所有功能的读写权限 包括对用户的操作 集群的操作等等

**Comment by ZQKC** [comment]
👍 感谢建议，这个地方确实存在一些问题，后续的2.x版本我们关注及看一下如何优化一下这个问题

**Comment by ZQKC** [comment]
3.x版本已具备自定义的能力，欢迎尝鲜～
