### ISSUE TITLE
监控告警中的报警策略问题

### ISSUE THREAD

**Issue by relleo** [didi/KnowStreaming#487]
同比变化率 这个策略 里面的 天 字段 出现 填写的与之后显示的不一致

![image](https://user-images.githubusercontent.com/13776250/163515989-7a6a2af0-c64f-4219-9e88-2e5df35ade01.png)

![image](https://user-images.githubusercontent.com/13776250/163516035-e8c7f46c-476a-40d6-8f46-d86322ccda1a.png)

**Comment by relleo** [comment]
能否在使用手册中 再详细 说明各报警策略的使用方法，填写实例等，谢谢

**Comment by ZQKC** [comment]
无更多反馈，关闭该Issue
