### ISSUE TITLE
关于logback的依赖修改

### ISSUE THREAD

**Issue by trockxi** [didi/KnowStreaming#488]
![image](https://user-images.githubusercontent.com/28647418/164353378-56dd2a04-eca7-4e22-8e0a-58935a3e727c.png)
因为logback版本存在漏洞，但在pom文件中未找到对应的项，需要帮查查哪里有依赖加载，谢谢
https://netsecurity.51cto.com/article/696683.html

**Comment by ZQKC** [comment]
后续我们关注一下，也欢迎贡献PR，解决该问题。
