### ISSUE TITLE
应用中文显示是乱码

### ISSUE THREAD

**Issue by RexHuang** [didi/KnowStreaming#497]
LogiKM version: 2.6.0
mysql: 8.0.27

mysql> select * from app;
+----+-----------+-------------+--------------------+------+-----------+------------+--------------------------------------+---------------------+---------------------+
| id | app_id    | name        | password           | type | applicant | principals | description                          | create_time         | modify_time         |
+----+-----------+-------------+--------------------+------+-----------+------------+--------------------------------------+---------------------+---------------------+
|  1 | dkm_admin | KM管理员 | km_kMl4N8as1Kp0CCY |    1 | admin     | admin      | KM管理员应用-谨慎对外提供 | 2022-06-27 02:10:29 | 2022-06-27 02:10:29 |
+----+-----------+-------------+--------------------+------+-----------+------------+--------------------------------------+---------------------+---------------------+
1 row in set (0.00 sec)

mysql中文显示正常，页面显示乱码
![image](https://user-images.githubusercontent.com/4577710/175849981-3197b34f-66df-4880-9078-95081d64bcfe.png)

**Comment by ZQKC** [comment]
可以修改一下库及表的编码格式看看

**Comment by xiexuejian** [comment]
这个问题解决了吗？修改库及表的编码格式为utf8之后，未解决。
