### ISSUE TITLE
申请完集群，没有在列表显示

### ISSUE THREAD

**Issue by RexHuang** [didi/KnowStreaming#498]
使用http://117.51.150.133:8080/
申请了集群，审批也通过了，应用id:appId_002760_cn
但是集群列表，没有显示新的集群

**Comment by ZQKC** [comment]
> 使用http://117.51.150.133:8080/ 申请了集群，审批也通过了，应用id:appId_002760_cn 但是集群列表，没有显示新的集群

集群管理-》申请集群 仅仅是提供一个给用户表达需求的入口，申请完成之后，需要管理员手动创建之后才会有的，具体的需要在运维管控侧，进行逻辑集群的创建。

**Comment by ZQKC** [comment]
重新设计后的3.x版本不存在该问题，因此关闭该Issue

**Comment by Leif160519** [comment]
> 使用http://117.51.150.133:8080/ 申请了集群，审批也通过了，应用id:appId_002760_cn 但是集群列表，没有显示新的集群

在运维管控里，点击这个物理集群，然后创建region，之后再创建逻辑集群信息，选择之前创建的region，即可创建逻辑集群
![image](https://user-images.githubusercontent.com/19452903/187582408-87aad62b-8606-4d7c-bf4b-397bf6ec153c.png)
![image](https://user-images.githubusercontent.com/19452903/187582422-aa15e885-8912-4ae7-929a-f26c9d3f4a4e.png)
