### ISSUE TITLE
LogiKM后台疯狂打印日志，可否控制日志级别？

### ISSUE THREAD

**Issue by xiaohaozifeifeifei** [didi/KnowStreaming#500]
LogiKM后台疯狂打印日志，可否控制日志级别？
目前info级别得日志过多，撑爆了磁盘。
<img width="834" alt="c358f749429e5ae980905c4e4ebfb46" src="https://user-images.githubusercontent.com/52524355/176838960-a462ff66-0ef6-478b-bb1e-d02ba5dcf085.png">

看启动文件start.sh还另外写了一份日志
<img width="207" alt="1a0eafbc5d79a9391a7ff61c4affe76" src="https://user-images.githubusercontent.com/52524355/176839029-6cb618f8-689a-432b-9444-31a816b2d1c9.png">

暂时没找到在哪里可以控制日志级别，有没有大佬可以提点一下得！谢谢！

**Comment by xiaohaozifeifeifei** [comment]
一周写了20G日志，扛不住啊！
求指点！

**Comment by ZQKC** [comment]
启动时可以指定日志文件，加一下 -Dlogging.config=./logback.xml ，logback.xml可以按照需要进行重新编写；

例如：
nohup java -jar -Dlogging.config=./logback.xml ./kafka-manager.jar --spring.config.location=./application.yml > /dev/null 2>&1 &

也可以关注一下都是什么日志，如果是一些无效的日志，也欢迎提PR对这部分进行优化。

**Comment by ZQKC** [comment]
无更多反馈，关闭该issue
