### ISSUE TITLE
strimzi  zookeeper 无法连接

### ISSUE THREAD

**Issue by damuji8** [didi/KnowStreaming#505]
我们是用strimzi运维的kafka集群。strimzi的zk是不对外暴露的，https://github.com/strimzi/strimzi-kafka-operator/issues/6047，这个logikm是不是必须设置zk地址。

**Comment by ZQKC** [comment]
1、当前2.x版本是必须设置ZK地址的，即将发布的3.x版本支持不填写ZK信息。
2、没有具体了解过strimzi，如果strimzi部署的Kafka是依赖于ZK的，那么他一定部署了ZK服务，可以检查一下Kafka关于ZK的配置从而看能否获取到ZK的信息。

**Comment by ZQKC** [comment]
无更多反馈，关闭该issue

**Comment by damuji8** [comment]
strimzi 有个第三方暴露zk端口的工具，已解决该问题。
