### ISSUE TITLE
连接jmx时使用公网端口问题

### ISSUE THREAD

**Issue by 1514466586** [didi/KnowStreaming#508]
正式环境中jmx通常不会开放公网端口,导致logikm连接不上kafka

**Comment by ZQKC** [comment]
> 正式环境中jmx通常不会开放公网端口,导致logikm连接不上kafka

近期我们优化一下，老哥有兴趣的话，欢迎贡献PR，对这块做一些优化啊。

**Comment by Huyueeer** [comment]
@ZQKC 其实我也有相同的疑虑，JMX不仅仅是监控的流出，还包含一部分可以操作的功能，肆意暴露是不是不太好？

**Comment by ZQKC** [comment]
> @ZQKC 其实我也有相同的疑虑，JMX不仅仅是监控的流出，还包含一部分可以操作的功能，肆意暴露是不是不太好，倒是可以加层认证。

1、确实直接暴露公网地址是不太友好，KM这块会去连接公网是因为中间有一个BUG，3.x版本我们会增加一个配置，让JMX连接的地址可配置。
2、安全上的话，JMX确实有一层认证会安全一些，KM也支持接入安全认证的JMX，不过一般来说Kafka正式环境都是内部使用的，不会有公网开放，所以一般情况下开放JMX也还好。

**Comment by ZQKC** [comment]
https://github.com/didi/KnowStreaming/blob/master/docs/dev_guide/%E8%A7%A3%E5%86%B3%E8%BF%9E%E6%8E%A5JMX%E5%A4%B1%E8%B4%A5.md

v3.0.0-beta.1版本已进行优化解决，可以尝鲜使用一下

**Comment by ZQKC** [comment]
无更多反馈，关闭该Issue
