### ISSUE TITLE
展示消费者及消费者组组页面，分页效果不起作用

### ISSUE THREAD

**Issue by dragon-hl** [didi/KnowStreaming#518]
**版本信息：**
API 版本: v3.0.0-beta.0
Centos7.4
JDK8

问题：
展示消费者及消费者组组页面，分页效果不起作用，数据未发生变化
![image](https://user-images.githubusercontent.com/63218901/187117476-3ef29990-678c-4404-b686-b6c563ee2207.png)

**Comment by ZQKC** [comment]
好的，我们关注一下

**Comment by chaixiaoxue** [comment]
大佬，这个没人认领的话，交给我把

**Comment by shirenchuang** [comment]
> 大佬，这个没人认领的话，交给我把

好滴
