### ISSUE TITLE
km-task 中使用 logi-job组件， 能否提供下开发指导文档？

### ISSUE THREAD

**Issue by lomodays207** [didi/KnowStreaming#522]
想自己去增加定时任务，开发步骤不是很清楚，能否麻烦提供下指导手册、开发注意事项等？ 

PS： 能附上logi-job调度底层实现原理的设计最好~   @ZQKC   麻烦大佬啦

**Comment by ZQKC** [comment]
好的，我们这周补充一下 🤝

**Comment by ZQKC** [comment]
已进行补充～

**Comment by lomodays207** [comment]
> 已进行补充～

看到了 ，辛苦了~！
