### ISSUE TITLE
3.0.0版本创建用户角色报错

### ISSUE THREAD

**Issue by QKChen1994** [didi/KnowStreaming#523]
请求url: http://***/logi-security/api/v1/role
报错信息：
\n### Error updating database.  Cause: java.sql.SQLException: (conn=2559) Field 'operation_methods' doesn't have a default value\n### The error may exist in com/didiglobal/logi/security/dao/mapper/OplogMapper.java (best guess)\n### The error may involve com.didiglobal.logi.security.dao.mapper.OplogMapper.insert-Inline\n### The error occurred while setting parameters\n### SQL: INSERT INTO logi_security_oplog  ( operator_ip, operator, operate_type, target, target_type, detail,   is_delete, app_name )  VALUES  ( ?, ?, ?, ?, ?, ?,   ?, ? )\n### Cause: java.sql.SQLException: (conn=2559) Field 'operation_methods' doesn't have a default value\n; (conn=2559) Field 'operation_methods' doesn't have a default value; nested exception is java.sql.SQLException: (conn=2559) Field 'operation_methods' doesn't have a default value

**Comment by Strangevy** [comment]
彦祖，可以分配给我吗

**Comment by shirenchuang** [comment]
> 彦祖，可以分配给我吗

好，你来

**Comment by ericshenjs** [comment]
临时解决方案:
ALTER TABLE logi_security_oplog CHANGE COLUMN operation_methods operation_methods VARCHAR(20) not null DEFAULT '';

![image](https://user-images.githubusercontent.com/7017653/187444112-b6c25dff-cdcd-4950-8bf2-a11f505dc6d0.png)

**Comment by Strangevy** [comment]
一、operationMethods在DDL中为必填且无默认值
二、operationMethods在包含该参数的构造方法没有在任何地方调用，该字段也未在任何地方赋值
![image](https://user-images.githubusercontent.com/7418194/187814644-3a2f4a9a-581b-40c1-92ae-a0b00d93ed9f.png)
三、在OplogDao的insert中会将Oplog复制给OplogPO再插入到库中，OplogPO不包含operationMethods字段
![image](https://user-images.githubusercontent.com/7418194/187815156-0c6023cf-1f62-4396-bcc3-87c71c1e82e1.png)
四、查询审计日志的接口的OplogVO也未包含该字段，在前端也无该字段的展示

缺失字段的地方是logi-security-spring-boot-starter暂无法修改，只能从DDL中去掉该字段或赋予默认值

**Comment by ZQKC** [comment]
> 从DDL中去掉该字段或赋予默认值

欢迎提个PR，从DDL中去掉该字段或赋予默认值
