### ISSUE TITLE
3.0.0dev版本controller切换重复显示

### ISSUE THREAD

**Issue by siriume** [didi/KnowStreaming#525]
如图
![image](https://user-images.githubusercontent.com/19361501/187367323-e9e6bb0b-84de-4b42-a7bf-febb0e6a7f94.png)

**Comment by shirenchuang** [comment]
这个问题补充一下： 是在kafka 3.2 版本的集群上， Kraft模式

**Comment by chenzhongyu11** [comment]
> 

我想看看这个问题！

**Comment by shirenchuang** [comment]
> > 
> 
> 我想看看这个问题！

好

**Comment by shirenchuang** [comment]
cloese
