### ISSUE TITLE
流量的监控粒度能不能做到ip级别

### ISSUE THREAD

**Issue by ruanliang-hualun** [didi/KnowStreaming#528]
客户端有多种消费方式
如果是直接 assign tp的方式去消费数据，不使用ConsumerGroup，服务端没法监控到这种消费者的流量情况

是否能做成监控每个消费者ip，展示对应ip的流量，在排查流量异常的时候可以快速定位到消费者

**Comment by shirenchuang** [comment]
因为设计到kafka的功能改造 该部分为商业特性。
