### ISSUE TITLE
Topic消息查询能按Timestamp排序就好了

### ISSUE THREAD

**Issue by superspeedone** [didi/KnowStreaming#534]
1、可以借鉴一下kafkatools，支持按Timestamp时间戳进行升序或降序查询消息
2、消息内容支持独立窗口预览，支持常用的格式化，例如：json/xml/text等等（kafkatools的消息预览布局就不错）

**Comment by shirenchuang** [comment]
Timestamp排序的可以先修改一下 ，格式化的 提一个单独的issue吧

**Comment by ZQKC** [comment]
感谢支持，已在beta.3版本中发布～
