### ISSUE TITLE
This script does not exist: deploy_KnowStreaming-offline.sh

### ISSUE THREAD

**Issue by maojunxyz** [didi/KnowStreaming#540]
The offline installation script described in the documentation does not exist in the actual package, please fix it.

**Comment by ZQKC** [comment]
> The offline installation script described in the documentation does not exist in the actual package, please fix it.

Thanks for your feedback!
The link in https://doc.knowstreaming.com/product/2-quick-start#212%E8%84%9A%E6%9C%AC%E9%83%A8%E7%BD%B2 we have fixed and If this problem still exists in other documents, feedback is welcome.
