### ISSUE TITLE
consumer模块无信息

### ISSUE THREAD

**Issue by mixsome** [didi/KnowStreaming#543]
容器化部署knowstreaming-3.0.0后 consumer列表无信息，topic和broker信息正常
kafka版本：2.1.1
![image](https://user-images.githubusercontent.com/22359872/188075932-29a4bd7b-8c49-4dc0-b56c-5a683e62edc9.png)
查看knowstreaming-manager日志有如下报错
![image](https://user-images.githubusercontent.com/22359872/188076391-bb6b96cb-46ca-44d3-a2fb-68b90402fd04.png)

**Comment by ZQKC** [comment]
> 容器化部署knowstreaming-3.0.0后 consumer列表无信息，topic和broker信息正常 kafka版本：2.1.1 ![image](https://user-images.githubusercontent.com/22359872/188075932-29a4bd7b-8c49-4dc0-b56c-5a683e62edc9.png) 查看knowstreaming-manager日志有如下报错 ![image](https://user-images.githubusercontent.com/22359872/188076391-bb6b96cb-46ca-44d3-a2fb-68b90402fd04.png)

1、该错误与Consumer模块无信息没有关系；
2、集群中是否有consumer信息？接入集群时，是否有什么错误提示？

**Comment by mixsome** [comment]
集群中有consumer信息。接入集群是没有相关错误提示，其他模式信息采集正常，查看consumer信息时，应用有如下报错。
![image](https://user-images.githubusercontent.com/22359872/188419432-fc24d0f6-6e77-4eaf-840e-a690cb5f0de9.png)
是否和kafka版本有关

**Comment by ZQKC** [comment]
> 集群中有consumer信息。接入集群是没有相关错误提示，其他模式信息采集正常，查看consumer信息时，应用有如下报错。 ![image](https://user-images.githubusercontent.com/22359872/188419432-fc24d0f6-6e77-4eaf-840e-a690cb5f0de9.png) 是否和kafka版本有关

这块在下一个版本做了兼容，到时候可以看一下是否还存在～

**Comment by mixsome** [comment]
ok  期待一下
