### ISSUE TITLE
集群overview界面能否突出显示整个集群数据量和数据大小

### ISSUE THREAD

**Issue by linsond-ocean** [didi/KnowStreaming#545]
集群overview界面能否突出显示整个集群数据量和数据大小，就放在topic总数、comsumer总数那个界面，现在集群数据量要通过筛选去查看，不是很直观。

**Comment by ZQKC** [comment]
感谢建议。
1、在多集群列表页面上会有，可以看到每个集群的数据量和数据大小；
2、确实在集群overview上补充该信息，信息会更全面，我们后续版本考虑一下如何添加，也好奇一般你们是在什么情况下，会去看一下这个数据，想了解一下你们的具体使用场景，从而看看是否还有更好的摆放位置。

![image](https://user-images.githubusercontent.com/4694454/188249507-9ed2cca2-96af-4002-a47c-141ce4e78161.png)

**Comment by ZQKC** [comment]
无更多反馈，关闭该Issue
