### ISSUE TITLE
topic-overview-top5只显示了topic的数据量（message），没有数据大小（size）

### ISSUE THREAD

**Issue by linsond-ocean** [didi/KnowStreaming#546]
topic-overview-top5只显示了topic的数据量，没有数据大小

**Comment by ZQKC** [comment]
![image](https://user-images.githubusercontent.com/4694454/188249460-72ebca09-5cd5-48ad-a035-8716fb894397.png)
需要将该指标勾选出来才会有～

**Comment by ZQKC** [comment]
无更多反馈，关闭该Issue
