### ISSUE TITLE
本地编译KnowStreaming-3.0.0-beta.0源码，idea启动后访问http://localhost:8080/，页面显示空白是啥原因啊？

### ISSUE THREAD

**Issue by wantyougogo** [didi/KnowStreaming#553]
1、下载源码导入idea，本地编译成功
![image](https://user-images.githubusercontent.com/44570840/188373706-33092967-8e2a-42ea-a283-b66b146a6f2f.png)

2、mysql库创建并初始化

3、elastic安装7.6.0版本并初始化

可是本地启动之后，访问http://localhost:8080/页面不显示内容，麻烦大佬们给指点指点！谢谢！

**Comment by wantyougogo** [comment]
![image](https://user-images.githubusercontent.com/44570840/188376588-d24ba5a0-a309-46c5-b237-363bf2fe459f.png)

es初始化的索引也都存在了

**Comment by wantyougogo** [comment]
![image](https://user-images.githubusercontent.com/44570840/188377957-62395a73-626a-4b00-90e9-dc97e8a34b2c.png)

**Comment by RenChauncy** [comment]
我的是mint系统,  可以到登陆页面.然后就报这个问题,

**Comment by ZQKC** [comment]
KnowStreaming-3.0.0-beta.0这个源码可能有些问题，可以再试一下v3.0.0-beta这个分支的源码

**Comment by ZQKC** [comment]
原因是前端包版本兼容问题导致，已修复

**Comment by wantyougogo** [comment]
> KnowStreaming-3.0.0-beta.0这个源码可能有些问题，可以再试一下v3.0.0-beta这个分支的源码

好的，感谢！
