### ISSUE TITLE
单机部署手册-容器部署中添加Docker部署方式

### ISSUE THREAD

**Issue by haoqi123** [didi/KnowStreaming#561]
俺发现[单机部署手册-容器部署](https://github.com/didi/KnowStreaming/blob/master/docs/install_guide/%E5%8D%95%E6%9C%BA%E9%83%A8%E7%BD%B2%E6%89%8B%E5%86%8C.md#213%E5%AE%B9%E5%99%A8%E9%83%A8%E7%BD%B2)缺少Docker的部署方式，如此好用的部署方式要不支持下

**Comment by shirenchuang** [comment]
好, 指派给你哈
