### ISSUE TITLE
报错：java.lang.NumberFormatException: For input string: "{"value":0,"relation":"eq"}"

### ISSUE THREAD

**Issue by chengyuan1029** [didi/KnowStreaming#563]
麻烦看下，是什么原因
环境：v3.0.0-beta.1，es：1.17.6，jdk：1.8.311，mysql：8.0.22
![image](https://user-images.githubusercontent.com/26703112/189026574-1d65e972-a2ba-44fd-93b1-7061b8efb23b.png)

删除topic会出现以下错误
![211f7b77476e7ed3bea3fd38a6cbb25](https://user-images.githubusercontent.com/26703112/189027141-a093261c-2fc2-4e01-aba0-f65e122bc664.jpg)

**Comment by lomodays207** [comment]
### 1、java.lang.NumberFormatException: For input string: "{"value":0,"relation":"eq"}"

这个问题应该是这块代码取ES total的时候有点小问题，有可能是ES版本问题

protected int handleESQueryResponseCount(ESQueryResponse response){
        if(null == response || null == response.getHits()
                || null ==response.getHits().getUnusedMap()){return -1;}

        return Integer.valueOf(response.getHits().getUnusedMap().**getOrDefault(TOTAL, 0)**.toString());
}

total 取出来是 jsonobject , 使用  Integer.valueOf 转换出错了 

![image](https://user-images.githubusercontent.com/16081650/189045339-f69db5a7-d853-404c-91a5-82bc4152c73b.png)


### 2、删除topic会出现的错误看起来是字段长度的问题，可以看看是详细日志是哪个表的？

**Comment by ZQKC** [comment]
> ### 1、java.lang.NumberFormatException: For input string: "{"value":0,"relation":"eq"}"
> 这个问题应该是这块代码取ES total的时候有点小问题，有可能是ES版本问题
> 
> protected int handleESQueryResponseCount(ESQueryResponse response){ if(null == response || null == response.getHits() || null ==response.getHits().getUnusedMap()){return -1;}
> 
> ```
>     return Integer.valueOf(response.getHits().getUnusedMap().**getOrDefault(TOTAL, 0)**.toString());
> ```
> 
> }
> 
> total 取出来是 jsonobject , 使用 Integer.valueOf 转换出错了
> 
> ![image](https://user-images.githubusercontent.com/16081650/189045339-f69db5a7-d853-404c-91a5-82bc4152c73b.png)
> 
> @ZQKC 大佬帮忙看看这块代码是否有问题，我本地已经修改好了
> 
> ### 2、删除topic会出现的错误看起来是字段长度的问题，可以看看是详细日志是哪个表的？

1、欢迎来个PR看看。
2、是logi_security_oplog这个表。

**Comment by ZQKC** [comment]
beta.2版本中已进行修复，升级版本后看是否解决该问题～

**Comment by ZQKC** [comment]
无更多反馈，关闭该问题～
