### ISSUE TITLE
删除topic报错

### ISSUE THREAD

**Issue by chengyuan1029** [didi/KnowStreaming#564]
麻烦看下，是什么原因
环境：v3.0.0-beta.1，es：1.17.6，jdk：1.8.311，mysql：8.0.22

![image](https://user-images.githubusercontent.com/26703112/189027582-084d8be2-4531-413c-9746-bc9a29cbccd4.png)

**Comment by ZQKC** [comment]
是 logi_security_oplog 这个表，设置的字段太短导致的
