### ISSUE TITLE
二进制部署提供的文件sql与源码中ddl_ks_km_sql文件不一致

### ISSUE THREAD

**Issue by haoqi123** [didi/KnowStreaming#574]
#### 问题发现
1. 使用脚本部署和手动部署的方式，启动manage添加kafka集群后会提示
```text
SQL: SELECT  id,cluster_phy_id,broker_id,host,port,jmx_port,start_timestamp,status,endpoint_map,create_time,update_time  FROM ks_km_broker     WHERE (cluster_phy_id = ?)
### Cause: java.sql.SQLSyntaxErrorException: (conn=6) Unknown column 'endpoint_map' in 'field list'
```
2. [单机部署手册-2.1.2、脚本部署](https://github.com/didi/KnowStreaming/blob/master/docs/install_guide/%E5%8D%95%E6%9C%BA%E9%83%A8%E7%BD%B2%E6%89%8B%E5%86%8C.md#2144knowstreaming-%E5%AE%9E%E4%BE%8B%E6%90%AD%E5%BB%BA)中[链接](https://s3-gzpu.didistatic.com/pub/knowstreaming/KnowStreaming-3.0.0-beta.tar.gz)中的`./init/sql/ddl-ks-km.sql`与源码中sql_table`ks_km_broker`的字段不一致，少了`endpoint_map`字段
3. [单机部署手册-2.1.4.4 KnowStreaming 实例搭建](https://github.com/didi/KnowStreaming/blob/master/docs/install_guide/%E5%8D%95%E6%9C%BA%E9%83%A8%E7%BD%B2%E6%89%8B%E5%86%8C.md#212%E8%84%9A%E6%9C%AC%E9%83%A8%E7%BD%B2)中两种部署方式文件中的sql同样与源码不一致

#### 解决建议
以源码为准，调整资源文件

**Comment by ZQKC** [comment]
好的，我们检查一下
