### ISSUE TITLE
系统topic无法进行副本扩缩容

### ISSUE THREAD

**Issue by devin-df** [didi/KnowStreaming#576]
系统topic无法进行扩缩副本以及副本迁移操作，即使选择了展示系统topic按钮，扩缩副本列表仍无系统topic（__consumer_offsets）贵司的尝试使用的网页也是同样的问题，应该不是bug
![1E91CB09-2F95-4077-99C7-FE457DE802BD](https://user-images.githubusercontent.com/24445549/189840534-9a9af45d-e684-4090-8722-941c4b944f86.png)

**Comment by ZQKC** [comment]
下一个版本会进行修复

**Comment by ZQKC** [comment]
已在beta.2版本中进行修复～
