### ISSUE TITLE
源码打包时前端工程报错

### ISSUE THREAD

**Issue by williom90320** [didi/KnowStreaming#578]
2.6版本，使用install_guide_cn.md 中的打包命令 mvn -Prelease-kafka-manager -Dmaven.test.skip=true clean install -U 打包时kafka-manager-console 报错，报错信息如下：请问是什么原因
[报错信息.txt](https://github.com/didi/KnowStreaming/files/9564666/default.txt)

**Comment by ZQKC** [comment]
> 2.6版本，使用install_guide_cn.md 中的打包命令 mvn -Prelease-kafka-manager -Dmaven.test.skip=true clean install -U 打包时kafka-manager-console 报错，报错信息如下：请问是什么原因 [报错信息.txt](https://github.com/didi/KnowStreaming/files/9564666/default.txt)

欢迎使用KnowStreaming 3.x版本，2.x版本后续会维护的越来越少

**Comment by ZQKC** [comment]
无更多反馈，关闭该Issue，后续如有打包问题，可以看一下FAQ，FAQ中已补充相关问题解决说明

**Comment by ppd0705** [comment]
我用的v3.0.0-beta.1， 也遇到同样的问题，需要升级到  v3.0.0-beta.2 才行
