### ISSUE TITLE
Controller检测结果不准确

### ISSUE THREAD

**Issue by conghuo** [didi/KnowStreaming#579]
问题：Cluster 集群 Controller检测结果与实现情况不符，如图：
![image](https://user-images.githubusercontent.com/22426964/190151889-dea6c8c4-a795-4db4-84fd-3e307a0290f0.png)

brokers状态
![image](https://user-images.githubusercontent.com/22426964/190152433-81b6bee9-b63b-4226-bcce-6af0c2c99e6c.png)

jmx 实际集群结果：
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/22426964/190152222-281f9705-1231-434c-8d7e-33cf57b775fe.png">

**Comment by ZQKC** [comment]
> 问题：Cluster 集群 Controller检测结果与实现情况不符，如图： ![image](https://user-images.githubusercontent.com/22426964/190151889-dea6c8c4-a795-4db4-84fd-3e307a0290f0.png)
> 
> brokers状态 ![image](https://user-images.githubusercontent.com/22426964/190152433-81b6bee9-b63b-4226-bcce-6af0c2c99e6c.png)
> 
> jmx 实际集群结果： <img alt="image" width="1116" src="https://user-images.githubusercontent.com/22426964/190152222-281f9705-1231-434c-8d7e-33cf57b775fe.png">

好的，下一个版本我们优化一下

**Comment by conghuo** [comment]
第二天早上 发现检查已通过，延时那么大的？
<img width="903" alt="image" src="https://user-images.githubusercontent.com/22426964/190298429-670d6f1f-c03b-493b-a642-8b25984f5273.png">

**Comment by ZQKC** [comment]
在beta.4版本中，我们优化一下

**Comment by ZQKC** [comment]
在最新版本中进行了优化，可以升级一下版本看一下效果～

**Comment by ZQKC** [comment]
无更多反馈，关闭该Issue
