### ISSUE TITLE
Consumer 中同一个ConsumerGroup 没有折叠

### ISSUE THREAD

**Issue by KittenLeo** [didi/KnowStreaming#580]
希望能类似2.6版本 同一个consumer group只显示一行， 点进去显示消费哪些 topic

**Comment by brodiehong** [comment]
我们在正式版本发布的时候，会做优化：consumer group列表每个consumer group只会展示一行，点开详情会出现topic列表，topic展开会显示partition的信息

**Comment by ZQKC** [comment]
后端已补充代码，等待前端补充后再关闭
