### ISSUE TITLE
Topic 中Messages选项下的Produce&Consume，点进去报404

### ISSUE THREAD

**Issue by KittenLeo** [didi/KnowStreaming#581]
Topic 中Messages选项下的Produce&Consume，点进去报404

**Comment by ZQKC** [comment]
> Topic 中Messages选项下的Produce&Consume，点进去报404

好的，下个版本我们优化一下

**Comment by ZQKC** [comment]
@GraceWalk

**Comment by ZQKC** [comment]
已在beta.3版本中修复～
