### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '2')

### ISSUE THREAD

**Issue by conghuo** [didi/KnowStreaming#592]
现象：前端突然无加载内容，通过流量器检查未发现 非200 的接口，但有如下错误
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '2')
    at layout-ece96e8b7bc06bcec116.js:1:1
(anonymous) @ layout-ece96e8b7bc06bcec116.js:1
Promise.then (async)
(anonymous) @ layout-ece96e8b7bc06bcec116.js:1
(anonymous) @ layout-ece96e8b7bc06bcec116.js:1
ec @ react-dom.production.min.js:114
Sj @ react-dom.production.min.js:161
unstable_runWithPriority @ react.production.min.js:25
pb @ react-dom.production.min.js:59
Ab @ react-dom.production.min.js:161
(anonymous) @ react-dom.production.min.js:161
V @ react.production.min.js:16
C.port1.onmessage @ react.production.min.js:24

尝试操作：
1、使用无痕浏览器，无效
2、整个系统重新部署后正常，过一段时间又出现此问题

![image](https://user-images.githubusercontent.com/22426964/190543548-3116773d-d533-42b6-836b-f2d0501d8b27.png)

**Comment by ZQKC** [comment]
我们关注一下

**Comment by ZQKC** [comment]
已在beta.2版本中修复
