### ISSUE TITLE
start_time not set when create reassign job

### ISSUE THREAD

**Issue by Mengqi777** [didi/KnowStreaming#598]
### Error updating database. Cause: java.sql.SQLIntegrityConstraintViolationException: (conn=2622) Column 'start_time' cannot be null ### The error may exist in URL [jar:file:/search/odin/kafka/KnowStreaming/libs/ks-km.jar!/BOOT-INF/lib/km-persistence-3.0.0-beta.jar!/mybatis/ReassignJob.xml] ### The error may involve com.xiaojukeji.know.streaming.km.persistence.mysql.reassign.ReassignJobDAO.addAndSetId-Inline ### The error occurred while setting parameters ### SQL: INSERT INTO ks_km_reassign_job (id, cluster_phy_id, reassignment_json, description, throttle_unit_byte, start_time, finished_time, creator, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ### Cause: java.sql.SQLIntegrityConstraintViolationException: (conn=2622) Column 'start_time' cannot be null ; (conn=2622) Column 'start_time' cannot be null; nested exception is java.sql.SQLIntegrityConstraintViolationException: (conn=2622) Column 'start_time' cannot be null

**Comment by ZQKC** [comment]
> 

使用的KS版本是？

**Comment by Mengqi777** [comment]
> 
自己编译的dev版本部署的。

虽然mysql建表语句中设置了NOT NULL DEFAULT '1971-1-1 00:00:00' 
```
`start_time` timestamp NOT NULL DEFAULT '1971-1-1 00:00:00' COMMENT '任务开始时间',
`finished_time` timestamp NOT NULL DEFAULT '1971-1-1 00:00:00' COMMENT '任务完成时间',
```
但实际运行的时候，如果不setStartTime/setFinishedTime，会报错，MySQL版本是
mysql  Ver 8.0.30 for Linux on x86_64 (MySQL Community Server - GPL)
