### ISSUE TITLE
角色管理：添加角色

### ISSUE THREAD

**Issue by yoohhwz** [didi/KnowStreaming#609]
version : 3.0 beat2
desc ：在角色管理功能添加角色时候，只选中 多集群管理查看 和 Test-Porduce 功能时，确定提交出现一下错误，刷新再次选中刚才那俩功能时候就可以正常提交了。报错如下:

Field "permission_id" doesn't have a default value ### The error may exists in com/didiglobal/logi/security/dao/mapper/RotePermissionMapper.java xxxxxxx

**Comment by ZQKC** [comment]
[#994](https://github.com/didi/KnowStreaming/issues/994)
