### ISSUE TITLE
能否支持mysql-connector-java来配置连接数据库

### ISSUE THREAD

**Issue by XW512** [didi/KnowStreaming#637]
由于现在大家使用的都是mysql-connector-java来连接数据库，而不是mariaDB的数据库，能否支持

**Comment by ZQKC** [comment]
> 由于现在大家使用的都是mysql-connector-java来连接数据库，而不是mariaDB的数据库，能否支持

1、这块的支持，需要调整的内容比较多，包括依赖的LogiCommon等，所以短期1-2天内支持不了。
2、数据库都是可以使用MySQL的，KS连接MySQL时，使用的驱动为mariaDB的驱动就可以了。

**Comment by XW512** [comment]
> > 由于现在大家使用的都是mysql-connector-java来连接数据库，而不是mariaDB的数据库，能否支持
> 
> 1、这块的支持，需要调整的内容比较多，包括依赖的LogiCommon等，所以短期1-2天内支持不了。 2、数据库都是可以使用MySQL的，KS连接MySQL时，使用的驱动为mariaDB的驱动就可以了。

我发现不使用mariaDB数据库启动不了，用默认的mariaDB驱动启动不了，用mysql-connector-java来连接数据库也启动不了

**Comment by ZQKC** [comment]
> 

使用的MySQL版本是？启动失败的错误信息是？
使用 driver-class-name: org.mariadb.jdbc.Driver 这个驱动，然后使用MySQL 5.7或者是 8.0的，应该是可以的。

**Comment by XW512** [comment]
> > 
> 
> 使用的MySQL版本是？启动失败的错误信息是？ 使用 driver-class-name: org.mariadb.jdbc.Driver 这个驱动，然后使用MySQL 5.7或者是 8.0的，应该是可以的。

报的错误如下：
Cause: java.lang.RuntimeException: Driver org.mariadb.jdbc.Driver claims to not accept jdbcUrl, jdbc:mysql://127.0.0.1:3306/know_streaming?useUnicode=true&characterEncoding=utf8&jdbcCompliantTruncation=true&allowMultiQueries=true&useSSL=false&alwaysAutoGeneratedKeys=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true

**Comment by XW512** [comment]
> > 
> 
> 使用的MySQL版本是？启动失败的错误信息是？ 使用 driver-class-name: org.mariadb.jdbc.Driver 这个驱动，然后使用MySQL 5.7或者是 8.0的，应该是可以的。

已经启动了，是因为配置的url的问题，一开始我以为不支持，所以就直接改了
