### ISSUE TITLE
3.0.0-beta.2版本初始化 MySQL 表及数据错误

### ISSUE THREAD

**Issue by afeng2016-s** [didi/KnowStreaming#638]
本地源码启动方式，在初始化 MySQL 表及数据时报错。
mysql版本：8.0.24

windows步骤如下：
1、创建数据库know_streaming，依次导入km-dist\init\sql下的五个sql文件
![image](https://user-images.githubusercontent.com/85676107/193004204-2c7ef008-0b28-416b-b2ba-e1144eff3726.png)
2、依次导入前四个文件，在导入第五个文件dml-logi.sql时报错如下：
![image](https://user-images.githubusercontent.com/85676107/193004616-49c02b4d-836c-4dd4-954a-2e9f57f9a81c.png)

centos7执行离线脚本安装时同样报错，步骤如下：
1、将安装包下载到本地并解压
2、执行安装脚本：sh deploy_KnowStreaming.sh，在初始化数据库时报错
![image](https://user-images.githubusercontent.com/85676107/193005538-57b5a9aa-33c1-4a2f-a226-63706a0f8a89.png)

**Comment by ZQKC** [comment]
欢迎使用最新的版本，该问题已在最新版本修复

**Comment by afeng2016-s** [comment]
> 使用最新版本，该问题已在最新版本修复

谢谢，问题已解决。
当我登录系统后，发现系统管理页面是空的。
![image](https://user-images.githubusercontent.com/85676107/193179717-174919f7-bbb1-4b33-8fb3-ed64f6763ba4.png)

**Comment by ZQKC** [comment]
> > 使用最新版本，该问题已在最新版本修复
> 
> 谢谢，问题已解决。 当我登录系统后，发现系统管理页面是空的。 ![image](https://user-images.githubusercontent.com/85676107/193179717-174919f7-bbb1-4b33-8fb3-ed64f6763ba4.png)

1、可以点击检查看一下console中是否有什么错误；
2、3.0.0正式版已发布，可以使用正式版；

**Comment by ZQKC** [comment]
无更多反馈，关闭该Issue
