### ISSUE TITLE
knowStreaming 连接 kafka 集群总是超时

### ISSUE THREAD

**Issue by forbearing** [didi/KnowStreaming#640]
### 我用的是 kafka 2.8.1, 使用 bitnami 的镜像, 用 docker-compose 启动的, knowStreaming 是最新版本 3.x, 也是 docker-compose 启动的. 但是在 knowStreaming ui 界面连接 kafka 的时候总是报超时的错误

**Comment by forbearing** [comment]
### 这是我的 kafka 配置(docker-compose 启动的)
![311665194066_ pic](https://user-images.githubusercontent.com/22474410/194682644-8f1e931a-7149-48e3-870c-217c50e76e99.jpg)

### 这个是超时报错信息:
![261665193953_ pic](https://user-images.githubusercontent.com/22474410/194682587-8badc2b5-b50f-4b18-a918-c509b1dfec9c.jpg)

### 这是超时报错日志:
![331665194207_ pic](https://user-images.githubusercontent.com/22474410/194682624-08ed42d5-2ffb-4f53-9337-88fef0a1b73b.jpg)

我不知道是不是我的 kafka jmx 配置错了, 我是开了 jmx 的, 并且 jmx 端口是 9999.

**Comment by haoqi123** [comment]
看上去像是kafak所在的容器与ks所在的容器不在一个网络中(使用上的问题)，有没有尝试给kafka添加network-bridge？

**Comment by forbearing** [comment]
问题找到了, 就是 kafka 和 knowStreaming 不在同一个网络导致的, 我把 kafka 集群的 network_mode 设置为 host 问题就解决了.
