### ISSUE TITLE
前端开发模式目前不能热部署？

### ISSUE THREAD

**Issue by kkwhichday** [didi/KnowStreaming#655]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

## 在这里提出你的问题
修改代码，后台不能自动编译，webpack的devServer配置都是没问题的。
output: {
    path:'/',
    publicPath: '/',
    filename: '[name].js',
    chunkFilename: '[name].js',
    library: 'layout',
    libraryTarget: 'amd',
  },
  devServer: {
    host: 'localhost',
    port: 8000,
    hot: true,
    inline: true,
    historyApiFallback: true,
    publicPath: `http://localhost:8000/`,

**Comment by GraceWalk** [comment]
是指修改文件后在终端看不到热更新信息吗？

**Comment by kkwhichday** [comment]
> 是指修改文件后在终端看不到热更新信息吗？ 如果是的话，是否是在 km-console 目录下启动的项目。如果是这种情况，可以分别到 km-console/packages/layout-clusters-fe 和 km-console/packages/config-manager-fe 下执行 npm run start，这样可以看到热更新信息。 如果不是，建议描述一下场景，我们具体定位一下问题。

我是在layout-clusters-fe内部 做的npm run start ，修改文件后，没有触发热更细，我的版本就是最新发布的3.0.0

**Comment by GraceWalk** [comment]
> > 是指修改文件后在终端看不到热更新信息吗？ 如果是的话，是否是在 km-console 目录下启动的项目。如果是这种情况，可以分别到 km-console/packages/layout-clusters-fe 和 km-console/packages/config-manager-fe 下执行 npm run start，这样可以看到热更新信息。 如果不是，建议描述一下场景，我们具体定位一下问题。
> 
> 我是在layout-clusters-fe内部 做的npm run start ，修改文件后，没有触发热更新，我的版本就是最新发布的3.0.0

是某些情况没有吗？还是完全没有？可以贴一个具体的例子方便我们排查问题吗？

**Comment by kkwhichday** [comment]
> 是某些情况没有吗？还是完全没有？可以贴一个具体的例子方便我们排查问题吗？

这是启动服务的控制台提示：
ℹ ｢wds｣: webpack output is served from http://localhost:8000/
ℹ ｢wds｣: Content not from webpack is served from /mnt/d/ideaproject/monitor/KnowStreaming-3.0.0/km-console/packages/layout-clusters-fe
ℹ ｢wds｣: 404s will fallback to /index.html
Build completed in 173.057s

⚠ ｢wdm｣:
WARNING in Conflict: Multiple assets emit different content to the same filename assets/image/iconfont.ttf

WARNING in Conflict: Multiple assets emit different content to the same filename assets/image/iconfont.woff

WARNING in Conflict: Multiple assets emit different content to the same filename assets/image/iconfont.woff2

WARNING in Conflict: Multiple assets emit different content to the same filename assets/image/iconfont.ttf

WARNING in Conflict: Multiple assets emit different content to the same filename assets/image/iconfont.woff2

WARNING in Conflict: Multiple assets emit different content to the same filename assets/image/iconfont.woff
ℹ ｢wdm｣: Compiled with warnings.

当我修改packages/layout-clusters-fe/src/pages/Login/login.tsx 这个文件里的html代码块时，后台不会触发更新。

**Comment by GraceWalk** [comment]
> 当我修改packages/layout-clusters-fe/src/pages/Login/login.tsx 这个文件里的html代码块时，后台不会触发更新。

我本地使用你提供的例子，修改 login.tsx 的 JSX 部分并保存文件后，触发了热更新，信息如下：
ℹ ｢wdm｣: Compiling...

Build completed in 2.037s

⚠ ｢wdm｣: 
WARNING in Conflict: Multiple assets emit different content to the same filename assets/image/iconfont.ttf

WARNING in Conflict: Multiple assets emit different content to the same filename assets/image/iconfont.woff2

WARNING in Conflict: Multiple assets emit different content to the same filename assets/image/iconfont.woff
ℹ ｢wdm｣: Compiled with warnings.

可以提供一下操作系统、Node 版本、Know Stearming 版本等信息吗？另外有对 webpack 配置进行改动吗？

**Comment by kkwhichday** [comment]
> > 当我修改packages/layout-clusters-fe/src/pages/Login/login.tsx 这个文件里的html代码块时，后台不会触发更新。
> 
> 我本地使用你提供的例子，修改 login.tsx 的 JSX 部分并保存文件后，触发了热更新，信息如下： ℹ ｢wdm｣: Compiling...
> 
> Build completed in 2.037s
> 
> ⚠ ｢wdm｣: WARNING in Conflict: Multiple assets emit different content to the same filename assets/image/iconfont.ttf
> 
> WARNING in Conflict: Multiple assets emit different content to the same filename assets/image/iconfont.woff2
> 
> WARNING in Conflict: Multiple assets emit different content to the same filename assets/image/iconfont.woff ℹ ｢wdm｣: Compiled with warnings.
> 
> 可以提供一下操作系统、Node 版本、Know Stearming 版本等信息吗？另外有对 webpack 配置进行改动吗？

ubuntu 18.04,   node v12.22.12, npm 6.14.16  ,Know Stearming3.0.0,  webpack没有动过

**Comment by GraceWalk** [comment]
> 

应该和 ubuntu 操作系统有关系，我在 stackoverflow 找到了类似的问题，你可以尝试一下。
https://stackoverflow.com/questions/39594574/webpack-hot-middleware-not-hot-reloading-on-ubuntu-with-react
