### ISSUE TITLE
使用prometheus对接ks暴露的指标，建议暴露topic每个分区的lag相关指标（比如lag数量，增长率）

### ISSUE THREAD

**Issue by Dignn** [didi/KnowStreaming#656]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   xxx </font>
* Operating System version :  <font size=4 color =red> xxx </font>
* Java version : <font size=4 color =red> xxx </font>

**Comment by WYAOBO** [comment]
收到，我会考虑实现该功能。

**Comment by ZQKC** [comment]
已进行补充，3.2版本可见，或者自行编译master分支即可～
