### ISSUE TITLE
Jmx 连接配置&问题解决

### ISSUE THREAD

**Issue by zwOvO** [didi/KnowStreaming#664]
- [√] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

### 重现该问题的步骤

1. 打开 https://github.com/didi/KnowStreaming/blob/master/docs/user_guide/faq.md
2. 点击 [Jmx 连接配置&问题解决](https://github.com/didi/KnowStreaming/blob/master/docs/user_guide/9-attachment#jmx-%E8%BF%9E%E6%8E%A5%E5%A4%B1%E8%B4%A5%E9%97%AE%E9%A2%98%E8%A7%A3%E5%86%B3) 
![image](https://user-images.githubusercontent.com/18533252/195364540-ac2729c0-c90a-44f1-b20b-cf24ea4ff24a.png)

### 预期结果
跳转到官网
![image](https://user-images.githubusercontent.com/18533252/195364989-39c7349f-4fdd-4f52-bf5d-8dd28af71895.png)

### 实际结果
![image](https://user-images.githubusercontent.com/18533252/195364893-7e25a837-a622-4741-b15c-c84474b8fe22.png)

**Comment by shirenchuang** [comment]
resolved
