### ISSUE TITLE
健康检查时间显示

### ISSUE THREAD

**Issue by so366** [didi/KnowStreaming#672]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

你是否希望来认领这个Bug。

「   Y   /   N  」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   xxx </font>
* Operating System version :  <font size=4 color =red> xxx </font>
* Java version : <font size=4 color =red> xxx </font>

### 重现该问题的步骤
<img width="898" alt="image" src="https://user-images.githubusercontent.com/39804141/195575046-5197f1e3-d823-45bb-9a8d-789be92501f4.png">
<img width="943" alt="image" src="https://user-images.githubusercontent.com/39804141/195575189-e20156ed-9bfc-448f-b99d-91d6baf56dff.png">

### 实际结果

---

如果有异常，请附上异常Trace:

```
Just put your stack trace here!
```

**Comment by chenzhongyu11** [comment]
可以指给我修复吗

**Comment by shirenchuang** [comment]
> 可以指给我修复吗

done
