### ISSUE TITLE
考虑引入prometheus/statsD存储监控数据

### ISSUE THREAD

**Issue by lynch0227** [didi/KnowStreaming#68]
由用户自行配置jmx exporter,然后再从prometheus里面获取监控数据.

**Comment by cobolbaby** [comment]
相比于 TSDB，用 TiDB 替代 MySQL 会是一个不错的选择，Zabbix 的数据库优化其实也是这个思路。

**Comment by ZQKC** [comment]
后续我们也关注一下这块，不过短期还是考虑在Kafka痛点问题上做优化～

**Comment by ZQKC** [comment]
已引入ES作为存储监控数据，同时数据也支持上报prometheus
