### ISSUE TITLE
建议子页面点开后，再点击左侧空白时自动关闭子页面

### ISSUE THREAD

**Issue by chenzhongyu11** [didi/KnowStreaming#680]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个优化建议。

 「   Y   /   N  」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   xxx </font>
* Operating System version :  <font size=4 color =red> xxx </font>
* Java version : <font size=4 color =red> xxx </font>

### 需要优化的功能点
比如这种页面，点击左侧之后可自动关闭详情页面：
![image](https://user-images.githubusercontent.com/35759818/195644171-e42ed231-6372-4fbb-b306-89be7742f580.png)

**Comment by shirenchuang** [comment]
这个交互  我倒是觉得没什么必要性  @华驰 可以看看这个交互建议

**Comment by shirenchuang** [comment]
如果弹窗出来的只是展示页面，我觉得你提议的交互方式不错，但是这个弹窗出来的页面有很多  功能操作项目
如果操作到一半，不小心点了其他地方，页面关了 会让人很抓狂

**Comment by brodiehong** [comment]
> 

抽屉有非常多的复杂操作项，避免误操作，暂时保留此交互方式😇

**Comment by ZQKC** [comment]
当前拒绝该优化，因此关闭该Issue，后续如有需要，可以重新提～
