### ISSUE TITLE
helm部署

### ISSUE THREAD

**Issue by so366** [didi/KnowStreaming#685]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个Bug。

 「   Y   /   N  」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   xxx </font>
* Operating System version :  <font size=4 color =red> xxx </font>
* Java version : <font size=4 color =red> xxx </font>

### 重现该问题的步骤

1. 根据https://doc.knowstreaming.com/product/2-quick-start#214%E5%AE%B9%E5%99%A8%E5%8C%96%E9%83%A8%E7%BD%B2文档操作，无法搭建一套正常的节点。情况如下
<img width="784" alt="image" src="https://user-images.githubusercontent.com/39804141/195777852-0150f5da-98ea-49e2-a773-545151f1118f.png">
主要原因是pvc未得到满足
<img width="404" alt="image" src="https://user-images.githubusercontent.com/39804141/195777926-2f5e51e0-00bb-4670-a988-26b1a0a76a0b.png">

### 预期结果

1、文档应该说明需要提前准备存储需求，已满足集群需要
2、文档应说明k8s资源应该预留多少CPU、内存才能满足

### 实际结果

根据文档，未成功部署

---

如果有异常，请附上异常Trace:

```
Just put your stack trace here!
```

**Comment by ZQKC** [comment]
@wangdongfang-aden 辛苦关注一下啊

**Comment by ahu0605** [comment]
为什么pending？集群的节点没有打标签？通过label match？

**Comment by one-two-my-gad** [comment]
> 我已经在k8s上成功了。 注意一下pvc设置即可，另外需要修改配置文件中 ![图片](https://user-images.githubusercontent.com/16282496/201808862-99986a82-4829-42ab-8059-ec66e649f85e.png) ![图片](https://user-images.githubusercontent.com/16282496/201809045-9deeeb3d-9f40-4d3a-af4c-609d3bf35760.png)

哈喽 想问下具体做了什么操作呢？新建一个pv么

**Comment by ZQKC** [comment]
> > 我已经在k8s上成功了。 注意一下pvc设置即可，另外需要修改配置文件中 ![图片](https://user-images.githubusercontent.com/16282496/201808862-99986a82-4829-42ab-8059-ec66e649f85e.png) ![图片](https://user-images.githubusercontent.com/16282496/201809045-9deeeb3d-9f40-4d3a-af4c-609d3bf35760.png)
> 
> 哈喽 想问下具体做了什么操作呢？新建一个pv么

确定使用哪一个登录校验的service，上面是默认的service，也可以自己实现相关接口，然后使用自定义的service

**Comment by wangdongfang-aden** [comment]
已更新相关文档
