### ISSUE TITLE
新增对zk有权限集群的支持

### ISSUE THREAD

**Issue by mgjiang** [didi/KnowStreaming#694]
对于zk有权限认证的集群 无法添加建议增加集群新增zk认证信息的填写框，并支持相应功能。
<img width="566" alt="image" src="https://user-images.githubusercontent.com/36840001/196165451-7a9c95c9-9b6a-40c0-9c4f-b80c76487cb4.png">

**Comment by luhea** [comment]
> 对于zk有权限认证的集群 无法添加建议增加集群新增zk认证信息的填写框，并支持相应功能。 <img alt="image" width="566" src="https://user-images.githubusercontent.com/36840001/196165451-7a9c95c9-9b6a-40c0-9c4f-b80c76487cb4.png">
可以参考看下目前的分支:dev_feature_zk_kerberos ,此分支是维护支持了zk的Kerberos认证，看下是否满足你的需求。
