### ISSUE TITLE
在刚刚创建的Topic中点击详情查看Message消息,会提示 Topic不存在

### ISSUE THREAD

**Issue by shirenchuang** [didi/KnowStreaming#697]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个Bug。

 「     N  」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   3.0 </font>
* Operating System version :  <font size=4 color =red> MacOs </font>
* Java version : <font size=4 color =red> 11 </font>

### 重现该问题的步骤

1.  在KnowStreaming创建一个新的Topic
   

2.  马上在平台上查看这个详情的Message模块

![image](https://user-images.githubusercontent.com/10442648/196380677-88617c10-2a6e-4a50-89aa-9b8f63a8439c.png)

   

3. 提示Topic不存在

4. 过了一会之后再次点击就不会出现 

### 预期结果

应该创建Topic的时候就能够展示，或者就算不能展示 也能够给一个友好的提示，比如：Topic正在创建中...等等

### 实际结果

提示Topic不存在。

PS：过了一小会儿之后就会回复正常

---

如果有异常，请附上异常Trace:

```
Just put your stack trace here!
```

**Comment by shirenchuang** [comment]
异常代码地方：
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/10442648/196386387-68fcf431-09ab-4bb5-806f-2f70b9e32af0.png">

**Comment by RenChauncy** [comment]
分给我吧
