### ISSUE TITLE
建议Consumer列表展示数据的时候给个提示: 数据最多有一分钟的延迟

### ISSUE THREAD

**Issue by shirenchuang** [didi/KnowStreaming#698]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个优化建议。

 「    N  」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   3.0 </font>
* Operating System version :  <font size=4 color =red> MacOS </font>
* Java version : <font size=4 color =red> 11 </font>

### 需要优化的功能点

消费组列表展示的地方，这里的数据会有最多1分钟的延迟，最好给个地方提示一下。

建议 刷新按钮 悬浮的时候能够提示

### 建议如何优化

![image](https://user-images.githubusercontent.com/10442648/196407711-0074e632-cb69-4576-a3ef-4c625b53d35e.png)

**Comment by brodiehong** [comment]
已排期优化。hover刷新按钮，提示“数据刷新间隔为1min，可能会有延迟”

**Comment by giraffe-tree** [comment]
@shirenchuang 来了来了

**Comment by Huanghaiting** [comment]
@shirenchuang can I try?

**Comment by superspeedone** [comment]
指派给我吧

**Comment by shirenchuang** [comment]
> @shirenchuang can I try?

已经指派给你了哈；  沟通交流的话 可以加我微信：  szzdzhp001    我拉你进迭代群呀

**Comment by Huanghaiting** [comment]
> 

好哒~已发送

**Comment by ZQKC** [comment]
已修复，关闭该Issue
