### ISSUE TITLE
重置Consumer Offset 弹窗文案优化, Consumer状态为Empty和Dead状态可以重置

### ISSUE THREAD

**Issue by shirenchuang** [didi/KnowStreaming#700]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个优化建议。

 「   N  」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   3.0 </font>
* Operating System version :  <font size=4 color =red> MacOS </font>
* Java version : <font size=4 color =red> 11 </font>

### 需要优化的功能点

Consumer状态为Empty和Dead状态可以重置

现在的弹窗只说了 Empty才可以重置。

![image](https://user-images.githubusercontent.com/10442648/196428680-4e3f02e3-8361-40b4-a0fd-81927e4e5ab6.png)

### 建议如何优化

文案改成：group处于Active, 重置失败(仅Empty | Dead 情况可重置)

**Comment by RichardZhengkay** [comment]
I'll follow up on this issue.

**Comment by RichardZhengkay** [comment]
The issue has been fixed, please follow up in time.
