### ISSUE TITLE
新增Topic的时候的测试消息大小功能不明显,希望文字能够明显一点

### ISSUE THREAD

**Issue by shirenchuang** [didi/KnowStreaming#725]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个Bug。

 「    N  」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   3.0 </font>
* Operating System version :  <font size=4 color =red> MacOs </font>
* Java version : <font size=4 color =red> 11 </font>

### 重现该问题的步骤

1. 点击 创建Topic

2. 点击测试消息大小

![在这里插入图片描述](https://img-blog.csdnimg.cn/9ba021645eaa436bb9063164211febc6.png)

### 预期结果

下面的  大小展示文字可以设置的明显一点

### 实际结果

消息太小了，容易被忽略, 一脸懵逼

---

如果有异常，请附上异常Trace:

```
Just put your stack trace here!
```

**Comment by brodiehong** [comment]
已排期优化

**Comment by Huanghaiting** [comment]
@brodiehong @shirenchuang 这个可以指派给我，需要改多大的字体？

**Comment by ZQKC** [comment]
> @brodiehong @shirenchuang 这个可以指派给我，需要改多大的字体？

我看有PR已经合入代码，请问这个issue已经修改好了吗？如果已修改完成，辛苦关闭一下Issue。
