### ISSUE TITLE
ks在打印错误日志过多,无法排查问题

### ISSUE THREAD

**Issue by 1514466586** [didi/KnowStreaming#738]
这种已知的错误，错误信息里面可以直接打印错误的原因，不需要打印stack信息，打印stack不能反映原因，而且日志量还多。
![275ed84985c880ea21e545fa79e88d0](https://user-images.githubusercontent.com/82856068/199148553-21e8a5bd-9202-4549-b08d-9e85198d7bc1.jpg)

**Comment by silent-night-no-trace** [comment]
1
