### ISSUE TITLE
部分icon在hover的时候，需要有背景色

### ISSUE THREAD

**Issue by shirenchuang** [didi/KnowStreaming#739]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个优化建议。

 「     N  」

### 需要优化的功能点

1.Cluster：健康度设置、编辑集群、刷新图表
2.Broker Overview：刷新图表、卡片Similar Config
3.Job：列表表头自定义列

4.Broker、Topic等等所有的列表的刷新，包括系统管理

具体需求为：以上icon在hover的时候，需要有背景色

**Comment by shirenchuang** [comment]
具体的改动   PRD 可以找我领取

**Comment by brodiehong** [comment]
补充：4.Broker、Topic等等所有的列表的刷新，包括系统管理

**Comment by Huanghaiting** [comment]
滴滴滴来啦~

**Comment by Huanghaiting** [comment]
@brodiehong 麻烦确认下，【腾讯文档】需求确认
https://docs.qq.com/doc/DTHBST0VLanF4aGpU

**Comment by brodiehong** [comment]
@Huanghaiting 已批注并补充完全

**Comment by Huanghaiting** [comment]
@brodiehong 忽略背景色那些，请问无文案的显示是这样？这个icon在hover的时候，方向有要求吗？上方还是下方之类的
![image](https://user-images.githubusercontent.com/17808807/199176012-4c7c633e-5c8b-4a52-973b-1b7d2b03ec4c.png)

**Comment by brodiehong** [comment]
无文案的只需要显示hover的背景色，不需要这个提示框 @Huanghaiting

**Comment by Huanghaiting** [comment]
> 无文案的只需要显示hover的背景色，不需要这个提示框 @Huanghaiting

好的，明白了🙂
