### ISSUE TITLE
升级新版本后控制台集群列表显示不全

### ISSUE THREAD

**Issue by yuyivic** [didi/KnowStreaming#741]
升级到最新版v3.1.0后，控制台显示kafka集群总数有21套，但是集群列表显示只有7套，剩余集群未显示，旧版本可以正常显示全部集群
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/22007456/199435920-8ae0178f-0737-451e-ba11-1cb1793456d6.png">
<img width="1446" alt="image" src="https://user-images.githubusercontent.com/22007456/199436362-9889ec55-6d13-4a27-af2e-a7472694821f.png">

**Comment by RichardZhengkay** [comment]
I'll follow up on this issue.

**Comment by RichardZhengkay** [comment]
After verification for many times, it has not been repeated, and the follow-up continues.

**Comment by ZQKC** [comment]
> After verification for many times, it has not been repeated, and the follow-up continues.

出现问题的原因是进行健康状态筛选时，如果集群的健康状态指标为空，则返回时就会出现集群缺少的情况。

例如：
1、多集群列表页的健康状态5个。
2、集群的健康状态指标查询ES时，如果查询不到，则该指标为空。此时，该空指标的状态不在5个状态里面，因此集群会被过滤掉不返回给前端。

解决方案：
可以考虑在获取集群指标时，如果集群健康状态指标不存在，则默认补充一个未知状态进去。
