### ISSUE TITLE
No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request

### ISSUE THREAD

**Issue by zy857189690** [didi/KnowStreaming#743]
### 环境信息

* KnowStreaming version :   3.1.0
* Operating System version : centos7
* Java version : 11

### 重现该问题的步骤

1. 使用扩缩副本功能 ，发现日志报错，但是实际后台已经缩容副本成功
   
![3acb5c16b0aff85216bac7e77effe0d](https://user-images.githubusercontent.com/42372535/199644213-aaba5b52-bb71-4258-9e24-3ff965cbefaa.jpg)

**Comment by RichardZhengkay** [comment]
Let me follow up on this issue.
