### ISSUE TITLE
有没有针对topic限流功能

### ISSUE THREAD

**Issue by dockerxu123** [didi/KnowStreaming#746]
- [x] 我在 [issues](https://github.com/didi/KnowStreaming/issues) 中并未搜索到与此相关的功能需求。
- [x] 我在 [release note](https://github.com/didi/KnowStreaming/releases) 已经发布的版本中并没有搜到相关功能.

你是否希望来认领这个Feature。

「   Y   /   N  」

## 这里描述需求

有没有针对topic限流功能，比如限制某个topic使用1M带宽

**Comment by ZQKC** [comment]
滴滴Kafka具备该能力，开源的Kafka暂时不具备Topic粒度的，但是支持Client粒度的。

**Comment by ZQKC** [comment]
暂时不支持，因此关闭该Issue
