### ISSUE TITLE
es index未自动创建

### ISSUE THREAD

**Issue by mixsome** [didi/KnowStreaming#750]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
- [ ] 
* KnowStreaming version :   <font size=4 color =red>   3.1.0 </font>
* Operating System version :  <font size=4 color =red> centos7 </font>
* Java version : <font size=4 color =red> 11.0.2 </font>

## 在这里提出你的问题
按照官方文档单节点手动部署Knowstreaming
1. 部署第一天显示正常，第二天平台无法显示监控信息及图像，
![image](https://user-images.githubusercontent.com/22359872/200248308-79990620-16af-45cc-8aef-a965b2af02b2.png)

 查询日志发现es index未自动创建
   
![image](https://user-images.githubusercontent.com/22359872/200248101-014e192c-84f6-431b-9c87-5e678d7b1640.png)

**Comment by everythingok001** [comment]
同样的问题

**Comment by WYAOBO** [comment]
查看一下ks的索引和模板是否存在和正常。ks的索引和模板都是以ks_kafka为前缀命名的。
如果有问题，尝试删除一下模板和索引，执行一下/km-dist/init/template/template.sh脚本重新初始化索引和模板，看看是否能解决问题。

**Comment by everythingok001** [comment]
@mixsome 如果是单节点安装es，把分片数调为1，副本数设置为0

**Comment by mixsome** [comment]
> @mixsome 如果是单节点安装es，把分片数调为1，副本数设置为0

是单节点es，分片数调为1，副本数设置为0后还是没有自动创建下一天的索引

**Comment by chao5go** [comment]
> > @mixsome 如果是单节点安装es，把分片数调为1，副本数设置为0
> 
> 是单节点es，分片数调为1，副本数设置为0后还是没有自动创建下一天的索引

我也遇到了，超过了最大shard数，然后调整了ES设置的最大shard数就好了
