### ISSUE TITLE
希望新增一个手动创建消费者组的功能

### ISSUE THREAD

**Issue by 1514466586** [didi/KnowStreaming#752]
可以手动在页面上创建一个group并且订阅topic

**Comment by luhea** [comment]
> 可以手动在页面上创建一个group并且订阅topic

hello，我理解的是：如果集群没开启acl那么任意的group都可以订阅topic，无需授权，如果开启了acl，目前的版本的acl菜单可以指定topic与group的订阅关系，不知道我的理解是否符合你的需求。

**Comment by 1514466586** [comment]
是的,现在的版本已经满足要求了,谢谢
