### ISSUE TITLE
接入集群时 集群配置不写的话 校验参数报错

### ISSUE THREAD

**Issue by duchang9264** [didi/KnowStreaming#754]
接入集群时 集群配置不写的话 校验参数报错 ，手动写“{}”, 就可以通过校验

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   3.1.0 </font>
* Java version : <font size=4 color =red> 1.8 </font>

### 建议如何优化
不写的话默认就可以通过校验

截图如下：

![image](https://user-images.githubusercontent.com/34643603/201079936-2e993cad-b325-4755-8377-c4c56f478b02.png)

报错如下：
JSON parse error: Cannot construct instance of `java.util.Properties` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value (''); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.Properties` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('') at [Source: (PushbackInputStream); line: 1, column: 164] (through reference chain: com.xiaojukeji.know.streaming.km.common.bean.dto.util.ValidateKafkaDTO["clientProperties"])

**Comment by limaiwang** [comment]
@duchang9264 这个问题修复了吗？没有修复的话，分给我吧
