### ISSUE TITLE
KnowStreaming-3.1.0 启动报错

### ISSUE THREAD

**Issue by wangxiajian** [didi/KnowStreaming#755]
KnowStreaming version : 3.1.0
Operating System version : centos7.9
Java version : 11

您好，我在使用脚本安装KnowStreaming-3.1.0，发现有报错
![image](https://user-images.githubusercontent.com/67364083/201252658-5ee3f6da-8d34-476e-aa72-7e5f9b71759f.png)

**Comment by ZQKC** [comment]
> KnowStreaming version : 3.1.0 Operating System version : centos7.9 Java version : 11
> 
> 您好，我在使用脚本安装KnowStreaming-3.1.0，发现有报错 ![image](https://user-images.githubusercontent.com/67364083/201252658-5ee3f6da-8d34-476e-aa72-7e5f9b71759f.png)

使用的脚本是？我们也验证一下看是否存在该问题

**Comment by wangxiajian** [comment]
wget https://s3-gzpu.didistatic.com/pub/knowstreaming/deploy_KnowStreaming.sh
sh deploy_KnowStreaming.sh

**Comment by ZQKC** [comment]
> wget https://s3-gzpu.didistatic.com/pub/knowstreaming/deploy_KnowStreaming.sh sh deploy_KnowStreaming.sh

1、更新了一下 deploy_KnowStreaming.sh 脚本，原先该脚本存在一些问题。
2、我测试了一下3.1.0的安装包，没有发现问题，我的环境是：
```
KnowStreaming version : 3.1.0
Operating System version : CentOS 7
Java version : 11
```

**Comment by wangxiajian** [comment]
好的，我重新进行测试一下，谢谢
