### ISSUE TITLE
Topic列表表头“健康分”改为"健康状态"，同Topic详情抽屉的健康状态，表格为文字“好”、“中”、“差”、“Down”、“Unknow”

### ISSUE THREAD

**Issue by brodiehong** [didi/KnowStreaming#758]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个优化建议。

 「   Y   /   N  」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   xxx </font>
* Operating System version :  <font size=4 color =red> xxx </font>
* Java version : <font size=4 color =red> xxx </font>

### 1.Topic列表表头“健康分”改为"健康状态"；
2.同Topic详情抽屉的健康状态，表格为文字“好”、“中”、“差”、“Down”、“Unknow”
3.列表排序，点击上箭头，为正序，差-->好；点击下箭头，为倒序，好-->差

**Comment by selectbook** [comment]
please assign to me agin :)

**Comment by zhugezifang** [comment]
分配给我吧
