### ISSUE TITLE
查看topic消息时，同时间的消息默认根据offset倒序

### ISSUE THREAD

**Issue by damuji8** [didi/KnowStreaming#769]
### 需要优化的功能点
查看topic消息时，同时间的消息默认根据offset倒序
![image](https://user-images.githubusercontent.com/31397673/203009505-7f255720-2c26-4c97-ab42-13dcad21030c.png)
另外文案也需要优化。

**Comment by ZQKC** [comment]
https://github.com/didi/KnowStreaming/issues/1041
