### ISSUE TITLE
KnowStreaming 新建topic 的时候，策略应该是删除或者压缩二选一，而不是都可选

### ISSUE THREAD

**Issue by zhugezifang** [didi/KnowStreaming#770]
![image](https://user-images.githubusercontent.com/28300167/203012376-aec7634e-667f-48a4-8b51-9c12fd4c5756.png)

KnowStreaming 新建topic 的时候，策略应该是删除或者压缩二选一，而不是都可选

**Comment by ZQKC** [comment]
应该和版本有关系，看了下最新的代码，两个可以都选。可以看看哪一个版本开始支持多选，然后进行多版本的控制。

![image](https://user-images.githubusercontent.com/4694454/203015343-32ccf29b-dbcb-4124-89cc-a11b51fa637d.png)

![image](https://user-images.githubusercontent.com/4694454/203015547-b2717ff5-8ac4-4e0c-a148-75cb3f5e382e.png)

**Comment by zhugezifang** [comment]
> 应该和版本有关系，看了下最新的代码，两个可以都选。可以看看哪一个版本开始支持多选，然后进行多版本的控制。
> 
> ![image](https://user-images.githubusercontent.com/4694454/203015343-32ccf29b-dbcb-4124-89cc-a11b51fa637d.png)
> 
> ![image](https://user-images.githubusercontent.com/4694454/203015547-b2717ff5-8ac4-4e0c-a148-75cb3f5e382e.png)

问下，第二个截图里面的代码是哪里的呀

**Comment by zhugezifang** [comment]
调研了一下kafka 不同版本关于cleanup.policy 参数设置
0.10.0 之前(包含0.10.0)版本string 类型
0.10.1 之后(包含0.10.1)版本list 类型

https://kafka.apache.org/0101/documentation.html

![image](https://user-images.githubusercontent.com/28300167/203285627-0c584860-6a05-4384-9823-1b52dc02ba36.png)

https://kafka.apache.org/0100/documentation.html

![image](https://user-images.githubusercontent.com/28300167/203285783-b1a9ced8-9640-41a3-a14a-249b87851ec7.png)

**Comment by ZQKC** [comment]
> 调研了一下kafka 不同版本关于cleanup.policy 参数设置 0.10.0 之前(包含0.10.0)版本string 类型 0.10.1 之后(包含0.10.1)版本list 类型
> 
> https://kafka.apache.org/0101/documentation.html
> 
> ![image](https://user-images.githubusercontent.com/28300167/203285627-0c584860-6a05-4384-9823-1b52dc02ba36.png)
> 
> https://kafka.apache.org/0100/documentation.html
> 
> ![image](https://user-images.githubusercontent.com/28300167/203285783-b1a9ced8-9640-41a3-a14a-249b87851ec7.png)

欢迎老哥来个PR啊

**Comment by zhugezifang** [comment]
好的呢，最近在整哈

**Comment by ZQKC** [comment]
后端已进行修复，前端待进行页面控制
