### ISSUE TITLE
KnowStreaming本地源码启动报错

### ISSUE THREAD

**Issue by allenwod** [didi/KnowStreaming#772]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个优化建议。

 「   Y     」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   master </font>
* Operating System version :  <font size=4 color =red> Mac </font>
* Java version : <font size=4 color =red> 1.8.0_312 </font>
* Maven 3.6.3
* Node v16.15.0
* MYSQL 8.0
* IDEA
* Elasticsearch 7.6
* Git

###报错截图
![image](https://user-images.githubusercontent.com/22765507/203208663-8bf72114-f3cf-4b89-8444-a353d50f674e.png)
![image](https://user-images.githubusercontent.com/22765507/203208680-ce37c5e5-003f-48c9-81a3-3a8e7a258066.png)
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22765507/203208741-96a836c9-d713-45d8-b5a1-029f774b8a79.png">

源码启动文档在初始化mysql数据和es索引数据指向【单机部署手册】中相关的步骤，由于文档引用的链接没有保持最新，从而引起报错

### 建议如何优化
建议优化【本地源码启动】文档，保持单一指责，避免跳转引用其他文档，减少外部影响，降低使用报错

**Comment by allenwod** [comment]
分配给我吧

**Comment by shirenchuang** [comment]
> 

done
