### ISSUE TITLE
修复2.6 版本批量数据迁移每次最多迁移10个topic bug

### ISSUE THREAD

**Issue by yws-tracy** [didi/KnowStreaming#785]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个Bug。

  Y 

### 重现该问题的步骤

1. 在专家服务/分区热点Topic 功能，如果使用批量功能，发现选了超过 10 个topic 之后， 点击确定没任何反映， 

<img width="999" alt="image" src="https://user-images.githubusercontent.com/34879511/204124815-f2e6f75a-a805-4fc6-bc7e-61169436c742.png">

2. 只有选择不超过10个 topic 时，才能提交成功。

3.  经过排查后发现是前端有个小问题
   const throttleIndex = Number(key.slice(0, 1));
   const throttleKey = key.slice(2);
写死了key取第一个字符，value 取后面的字符， 当超过10个topic时，就有问题了 ，比如： 10-minThrottle  key就是1， value 是-minThrottle，这是不对的，导致 paramsData.length != data.length 无法提交

<img width="342" alt="image" src="https://user-images.githubusercontent.com/34879511/204125011-d8303c0e-f98a-4e4a-9111-29d187cbfe83.png">

<img width="764" alt="image" src="https://user-images.githubusercontent.com/34879511/204125054-6bb6c340-c165-4c3a-ab32-742649dde6f7.png">

### 预期结果
当topic 超过10个时，应该能正确提交任务
### 实际结果

实际前端有bug，不应该写死取第一个字符作为index， 第二个字符后的字符作为key，

**Comment by lucasun** [comment]
fixed in #786
