### ISSUE TITLE
查看Zookeeper 详情目录结构搜索文案优化建议

### ISSUE THREAD

**Issue by Huanghaiting** [didi/KnowStreaming#793]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个优化建议。

 「   Y  /  N 」

### 环境信息

https://demo.knowstreaming.com/

### 需要优化的功能点
未选中时搜索无效，且文案有歧义并未表达清晰搜索的范围
![image](https://user-images.githubusercontent.com/17808807/204283661-4d74bb8e-d994-4777-a5c5-c8745c4e9434.png)

### 建议如何优化
建议更改为“选中节点后进行搜索”，或更优文案。

**Comment by PenceXie** [comment]
这是个非常好的建议，确实可以消除用户歧义，我们优化下
