### ISSUE TITLE
最新master分支代码 partitionService.listPartitionFromCacheFirst 启动发生报错

### ISSUE THREAD

**Issue by Daizhengming** [didi/KnowStreaming#802]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

## 在这里提出你的问题

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/31427354/205259122-9a4e02dd-bb30-4cdf-b814-5c5dbb2bc4d7.png">

错误信息 
`java: 无法将接口 com.xiaojukeji.know.streaming.km.core.service.partition.PartitionService中的方法 listPartitionFromCacheFirst应用到给定类型;
  需要: java.lang.Long,java.lang.String
  找到: java.lang.Long
  原因: 实际参数列表和形式参数列表长度不同`

<img width="638" alt="image" src="https://user-images.githubusercontent.com/31427354/205259406-7fc212b2-2c07-4825-9541-6c7610ebaa46.png">

listPartitionFromCacheFirst 方法是否漏了 topicName?

**Comment by ZQKC** [comment]
我看一下啊，应该是同步代码时，少同步了一些

**Comment by Daizhengming** [comment]
Hi,this is Abner Dai.
  I have received your letter.I will reply to your letter as soon as possible.
                                                                   Abner Dai
