### ISSUE TITLE
访问knowStreaming 提示 org.thymeleaf.exceptions.TemplateInputException: Error resolving template [layout/index], template might not exist or might not be accessible by any of the configured Template Resolvers

### ISSUE THREAD

**Issue by guokexue123** [didi/KnowStreaming#821]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个Bug。

 「   Y   /   N  」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   xxx </font>
* Operating System version :  <font size=4 color =red> xxx </font>
* Java version : <font size=4 color =red> xxx </font>

### 重现该问题的步骤

1. xxx
   

2. xxx
   

3. xxx

### 实际结果

---

如果有异常，请附上异常Trace:

```
Just put your stack trace here!
```

**Comment by ZQKC** [comment]
直接启动，会缺少前端静态资源文件，需要执行一下`mvn clean package`之后再进行启动即可。

执行`mvn clean package`之后，会将前端资源文件打包并输出到km-rest/xxx/resource/template目录下。
