### ISSUE TITLE
进行Kafka-Controller健康巡检时，由于查询ES异常导致会抛出空指针异常，但是日志提示不明显

### ISSUE THREAD

**Issue by ZQKC** [didi/KnowStreaming#869]
错误的原因是查询ES失败导致的，但是错误日志提示不明显，期望优化一下错误日志：

![image](https://user-images.githubusercontent.com/4694454/212004908-33af72c2-85b6-41a5-bd92-ec0f53085bfd.png)

**Comment by fengqiongfeng** [comment]
申请认领
