### ISSUE TITLE
测试部分代码集成testcontainers

### ISSUE THREAD

**Issue by haoqi123** [didi/KnowStreaming#870]
- [x] 我在 [issues](https://github.com/didi/KnowStreaming/issues) 中并未搜索到与此相关的功能需求。
- [x] 我在 [release note](https://github.com/didi/KnowStreaming/releases) 已经发布的版本中并没有搜到相关功能.

你是否希望来认领这个Feature。

「   Y    」

## 这里描述需求

是否可使用 `https://www.testcontainers.org/` 对测试部分代码进行调整？
1. 可以做到无需额外环境依赖配置，再也不用操心测试时版本适配的问题
2. 使其能拥有良好的代码测试,理论上可以降低bug数量
俺很有意愿为ks添加这部分代码

**Comment by ZQKC** [comment]
> 

感谢建议。我觉得可以的，不过后续如果有这块的贡献，辛苦先提供一个最小功能集的PR，搞一个测试代码的规范，后续就按照这个规范逐步补充。

**Comment by haoqi123** [comment]
> > 
> 
> 感谢建议。我觉得可以的，不过后续如果有这块的贡献，辛苦先提供一个最小功能集的PR，搞一个测试代码的规范，后续就按照这个规范逐步补充。

这真是太令人兴奋了，等我提交PR

**Comment by haoqi123** [comment]
等我再优化一下
