### ISSUE TITLE
Similar Config: NO

### ISSUE THREAD

**Issue by bigkjp97** [didi/KnowStreaming#872]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

## 在这里提出你的问题
Hello，我想问下，Broker Overview里面Similar Config指标显示的是NO，检查了配置文件除了id、listeners其他都是一致的，这个指标是基于什么判断呢？

**Comment by ZQKC** [comment]
> * [x]  我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
> 
> ## 在这里提出你的问题
> Hello，我想问下，Broker Overview里面Similar Config指标显示的是NO，检查了配置文件除了id、listeners其他都是一致的，这个指标是基于什么判断呢？

可以看一下mysql的ks_km_broker_config表看一下有哪些数据不一样，当前会忽略 "broker.id", "listeners", "name", "value" 这四个配置的差异。

**Comment by bigkjp97** [comment]
好的，谢谢

**Comment by chengang2** [comment]
advertised.listeners 这个也需要忽略 @ZQKC
