### ISSUE TITLE
SCRAM-SHA-512 不支持

### ISSUE THREAD

**Issue by las1991** [didi/KnowStreaming#878]
org.apache.kafka.common.errors.SaslAuthenticationException: Authentication failed due to invalid credentials with SASL mechanism SCRAM-SHA-512

**Comment by ZQKC** [comment]
> org.apache.kafka.common.errors.SaslAuthenticationException: Authentication failed due to invalid credentials with SASL mechanism SCRAM-SHA-512

这个是什么情况下报的错误？填写的信息是？

**Comment by las1991** [comment]
> 

{
	"security.protocol": "SASL_PLAINTEXT",
	"sasl.mechanism": "SCRAM-SHA-512",
	"sasl.jaas.config": "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"admin\" password=\"admiin\";"
}

**Comment by las1991** [comment]
> > org.apache.kafka.common.errors.SaslAuthenticationException: Authentication failed due to invalid credentials with SASL mechanism SCRAM-SHA-512
> 
> 这个是什么情况下报的错误？填写的信息是？

{
"security.protocol": "SASL_PLAINTEXT",
"sasl.mechanism": "SCRAM-SHA-512",
"sasl.jaas.config": "org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin";"
}

**Comment by ZQKC** [comment]
> {
> "security.protocol": "SASL_PLAINTEXT",
> "sasl.mechanism": "SCRAM-SHA-512",
> "sasl.jaas.config": "org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin";"
> }

```
{
"security.protocol": "SASL_PLAINTEXT",
"sasl.mechanism": "SCRAM-SHA-512",
"sasl.jaas.config": "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"admin\" password=\"admin\";"
}
```
试一下这个看是否可以，你贴的缺少`\`了。

**Comment by las1991** [comment]
> > {
> > "security.protocol": "SASL_PLAINTEXT",
> > "sasl.mechanism": "SCRAM-SHA-512",
> > "sasl.jaas.config": "org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin";"
> > }
> 
> ```
> {
> "security.protocol": "SASL_PLAINTEXT",
> "sasl.mechanism": "SCRAM-SHA-512",
> "sasl.jaas.config": "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"admin\" password=\"admin\";"
> }
> ```
> 
> 试一下这个看是否可以，你贴的缺少`\`了。

实际是有\的，不加的话，页面json编辑器不通过，github上回复的问题

**Comment by ZQKC** [comment]
> > > {
> > > "security.protocol": "SASL_PLAINTEXT",
> > > "sasl.mechanism": "SCRAM-SHA-512",
> > > "sasl.jaas.config": "org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin";"
> > > }
> > 
> > 
> > ```
> > {
> > "security.protocol": "SASL_PLAINTEXT",
> > "sasl.mechanism": "SCRAM-SHA-512",
> > "sasl.jaas.config": "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"admin\" password=\"admin\";"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 试一下这个看是否可以，你贴的缺少`\`了。
> 
> 实际是有\的，不加的话，页面json编辑器不通过，github上回复的问题

那这个认证信息对么？看这个错误，是kafka-client返回的错误，出现错误的原因要么是配置问题，要么是这个认证用户本身就有问题。

**Comment by las1991** [comment]
> > > > {
> > > > "security.protocol": "SASL_PLAINTEXT",
> > > > "sasl.mechanism": "SCRAM-SHA-512",
> > > > "sasl.jaas.config": "org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin";"
> > > > }
> > > 
> > > 
> > > ```
> > > {
> > > "security.protocol": "SASL_PLAINTEXT",
> > > "sasl.mechanism": "SCRAM-SHA-512",
> > > "sasl.jaas.config": "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"admin\" password=\"admin\";"
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 试一下这个看是否可以，你贴的缺少`\`了。
> > 
> > 
> > 实际是有\的，不加的话，页面json编辑器不通过，github上回复的问题
> 
> 那这个认证信息对么？看这个错误，是kafka-client返回的错误，出现错误的原因要么是配置问题，要么是这个认证用户本身就有问题。

不好意思，解决了
