### ISSUE TITLE
只读权限的用户仍然可以操作User和Acl

### ISSUE THREAD

**Issue by zhaoli2333** [didi/KnowStreaming#879]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   3.2.0 </font>
* Operating System version :  <font size=4 color =red> centos </font>
* Java version : <font size=4 color =red> 11 </font>

### 重现该问题的步骤

1. 创建新角色readonly，只勾选“多集群管理查看”权限
2. 创建用户并绑定角色readonly
3. 登陆该用户，仍然可以在Security下的Acls和Users模块进行修改和删除操作

**Comment by ZQKC** [comment]
与 #727 重复，关闭一个
