### ISSUE TITLE
Consumers Groups 显示数量不足

### ISSUE THREAD

**Issue by firmament2008** [didi/KnowStreaming#885]
kafka版本 2.0.1
2023.02.02 通过docker-compos部署
    image: knowstreaming/knowstreaming-manager:latest
    image: knowstreaming/knowstreaming-ui:latest
    image: docker.io/library/elasticsearch:7.6.2
    image: knowstreaming/knowstreaming-manager:latest
    image: knowstreaming/knowstreaming-mysql:latest

我通过kafka-manager  查看 kafka集群是 0.8.2.0   , Consumers 数量是57 ， 但用  KS只显示了10个且翻页功能也无法显示

**Comment by ZQKC** [comment]
master分支已修复，下个版本会修复该问题。

**Comment by firmament2008** [comment]
请问是在那个模块修复的？ km-console 还是其他？

**Comment by ZQKC** [comment]
> 请问是在那个模块修复的？ km-console 还是其他？

是的，km-console是ks的前端代码
