### ISSUE TITLE
后台日志报空指针 类型转换错误

### ISSUE THREAD

**Issue by arjun-go-go** [didi/KnowStreaming#912]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   3.2.0</font>
* Operating System version :  <font size=4 color =red> debian10 </font>
* Java version : <font size=4 color =red> 11 </font>

![b6caf5f3df8fbcbc847a73cfe80d02ea](https://user-images.githubusercontent.com/32705536/218430028-3ea19631-b580-436a-b736-f0f7f8539c27.png)

![image](https://user-images.githubusercontent.com/32705536/218431485-413612e5-bd12-45d6-b68e-94005a60a40d.png)

```
Just put your stack trace here!
```

**Comment by slhu997** [comment]
我计划修复一下该问题
