### ISSUE TITLE
KRAFT模式的kafka不能通过controller健康检查

### ISSUE THREAD

**Issue by ZhiYinZhang** [didi/KnowStreaming#924]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

## 在这里提出你的问题
kafka
docker部署，版本3.3.1，单节点，kraft模式

knowstreaming 
docker部署 镜像版本0.7.0

不能通过controller数量检查
![image](https://user-images.githubusercontent.com/36368381/219002392-17517df0-30af-441c-a7f7-b94200d35fcd.png)

是什么地方有问题，还是bug

**Comment by ZQKC** [comment]
这块有什么报错信息么？比如JMX连接失败，或者什么的？

**Comment by ZhiYinZhang** [comment]
重启后可以了。。。
