### ISSUE TITLE
为什么brokers状态异常呢

### ISSUE THREAD

**Issue by hdygxsj** [didi/KnowStreaming#984]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

## 在这里提出你的问题
为什么brokers状态异常呢，
![WechatIMG429](https://user-images.githubusercontent.com/35210666/226295108-1f133e8d-70d5-4ba8-8568-a99c0007de7e.jpeg)

**Comment by ZQKC** [comment]
> * [ ]  我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
> 
> ## 在这里提出你的问题
> 为什么brokers状态异常呢， ![WechatIMG429](https://user-images.githubusercontent.com/35210666/226295108-1f133e8d-70d5-4ba8-8568-a99c0007de7e.jpeg)

1、使用的是3.3.0版本么？
2、使用一段时间之后显示还是这样的么？
3、看一下集群那一块，看看是否有什么地方是异常的。

**Comment by ZQKC** [comment]
无更多反馈，关闭该Issue
