### ISSUE TITLE
关于lib中依赖jar包的安全优化

### ISSUE THREAD

**Issue by killinitzero** [didi/KnowStreaming#985]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

## 在这里提出你的问题
这边安装了ks 最新的3.3 版本
服务器做了软件的安全扫描
发现安装了ks之后安全扫描了我们的jar发现lib里面很多jar版本都比较低有大量的安全风险
lib依赖的版本是否可以根据目前最新的来保持更新
或者有没有办法自行修复lib里面版本低的问题

**Comment by killinitzero** [comment]
能把这个相关依赖升级到 spring-boot-starter-parent 吗  log4j 用2.20的吗

**Comment by ZQKC** [comment]
> ![image](https://user-images.githubusercontent.com/16663021/227439488-6ed1a9e2-af3d-4d4f-b975-e2fcdf8dba83.png)
> 
> Jackson Databind 这个包的版本漏洞比较多建议升级 但是升级到2.13的版本之后 启动就报错了
> 
> 2023-03-24 13:59:22.865 [main] ERROR class=o.s.boot.web.embedded.tomcat.TomcatStarter||Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'formContentFilter' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.filter.OrderedFormContentFilter]: Factory method 'formContentFilter' threw exception; nested exception is java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/util/JacksonFeature 2023-03-24 13:59:23.033 [main] ERROR class=org.springframework.boot.SpringApplication||Application run failed org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat

可以关注 https://github.com/didi/KnowStreaming/pull/997 这个PR，看是否可以解决。
