### ISSUE TITLE
权限ACL管理中，消费组列表展示错误

### ISSUE THREAD

**Issue by velee** [didi/KnowStreaming#991]
<img width="476" alt="image" src="https://user-images.githubusercontent.com/8765691/229014777-04a33bbe-c5a9-4e10-9d5f-b57a8079f026.png">

消费组列表里面展示的是Topic列表

**Comment by HZSUZJ** [comment]
我来修复该问题

**Comment by lucasun** [comment]
> 我来修复该问题
修复后欢迎PR

**Comment by HZSUZJ** [comment]
> > 我来修复该问题
> > 修复后欢迎PR

已提交修复的PR
